feat: update whats new page
ovh/design-system pull request #102
Opened 2023-07-18 13:56 UTC by skhamvon

2023-07-18 15:06 UTC, dpellier commented on packages/doc/src/whats-new.mdx
> +g
typo ?

2023-07-18 15:37 UTC, astagnol requested changes

2023-07-18 15:37 UTC, astagnol commented on packages/doc/src/whats-new.mdx
>  As it is a major version, you have to do the [migration guide 13.x to 14.x](/story/ovhcloud-design-system-what-s-new-migration-guide-13-x-to-14-x--page)
This sentence belongs to v14.0.0, should be added after line 38

2023-07-19 10:07 UTC, astagnol approved these changes

2023-07-19 10:24 UTC, ovh-cds commented
CDS Report build-storybook#955.0 ✘  
* 
  * build ✘

2023-07-19 12:21 UTC, merged