Feat/search bar
ovh/design-system pull request #103
Opened 2023-07-19 09:36 UTC by aesteves60

2023-07-20 07:00 UTC, dpellier requested changes
Change on select did have an impact
<img width="196" alt="Capture d’écran 2023-07-20 à 08 58 53" src="https://github.com/ovh/design-system/assets/1390934/c7189ed5-455f-4b30-a765-4401d9db4ee2">

Also would be nice to normalize button right border-radius and select/input left one

2023-07-20 07:01 UTC, dpellier commented on packages/stencil/components/select/src/components/osds-select/osds-select.scss
> -    &.opened {
can't you override what you need directly in the search bar style?

2023-07-20 08:20 UTC, aesteves60 commented on packages/stencil/components/search-bar/src/components/osds-search-bar/osds-search-bar.scss
> +  cursor: not-allowed;
If I remove this the button haven't the cursor not-allowed

2023-07-20 09:02 UTC, aesteves60 commented on packages/stencil/components/select/src/components/osds-select/osds-select.scss
> -    &.opened {
No that's because this class was duplicated in the styles/osds-select.size.scss file

2023-07-20 09:06 UTC, aesteves60 commented on packages/stencil/components/search-bar/src/components/osds-search-bar/osds-search-bar.tsx
> +            if (isEnter || isSpace) {
yes but the button don't emit the event `odsSearchSubmit`

2023-07-20 12:15 UTC, dpellier commented on packages/stencil/components/search-bar/src/components/osds-search-bar/osds-search-bar.scss
> +  cursor: not-allowed;
Then it's an issue to fix on the button component.
@astagnol can you confirm it is the expected cursor also for disabled button?

2023-07-20 12:16 UTC, dpellier commented on packages/stencil/components/search-bar/src/components/osds-search-bar/osds-search-bar.tsx
> +            if (isEnter || isSpace) {
you can catch the button event, prevent its propagation and emit your own, that way you don't duplicate the keyDown behavior

2023-07-24 12:58 UTC, astagnol requested changes
In contrasted, a border should de displayed for osds-button like this:
![Capture d’écran 2023-07-24 à 14 55 05](https://github.com/ovh/design-system/assets/53512103/9d5f8103-48de-4d0d-ae4e-c20124a488d5)

You need to add search bar to scripts/testing-report/index.html

2023-07-25 13:20 UTC, astagnol requested changes
- Select: should have cursor not allowed when search-bar is disabled
- Icon in osds-button is not correctly aligned vertically. It seems we should add an inline-flex on class button__centered-text?

2023-07-27 13:32 UTC, dpellier requested changes
`border-radius` are different between the left (input) and the right (button), would be nice to have the same.

2023-07-27 16:12 UTC, astagnol requested changes
- Button border-radius right top & right bottom should be 4px
- In storybook, when you set `contrasted` to true, Button size is changing
- In Storybook, with filled field, when you set `contrasted` or `loading`, content is cleared. For disabled state I think it is normal to clear the field but with `contrasted` and `loading` it doesn't seem correct

2023-08-01 09:47 UTC, astagnol approved these changes

2023-08-01 09:53 UTC, astagnol commented
-resolve conflicts

Will be resolved in separated tickets/PR:
- accessibility: no focus on clear icon button
- Input: click on clear icon should put focus back on Input
- Input: is clearable from 1 character

2023-08-01 12:49 UTC, ovh-cds commented
CDS Report build#1056.0 ✘  
* 
  * build ✘

2023-08-01 13:46 UTC, ovh-cds commented
CDS Report build#1056.1 ✘  
* 
  * build ✘

2023-08-02 08:25 UTC, aesteves60 commented on packages/stencil/components/clipboard/src/global.test.ts
To remove

2023-08-02 08:25 UTC, aesteves60 commented on packages/stencil/components/search-bar/package.json
> +    "@ovhcloud/ods-stencil-component-dev": "^15.0.1"
@dpellier should I need to add @ovhcloud/ods-component-icon ?

2023-08-03 08:09 UTC, astagnol requested changes
Alignment issue with opened Select
![Capture d’écran 2023-08-03 à 10 08 12](https://github.com/ovh/design-system/assets/53512103/55e9561e-5817-4955-b0a9-7cfc1a109eee)

2023-08-04 08:45 UTC, astagnol approved these changes

2023-08-04 13:39 UTC, merged