fix(input): block actions if disabled
ovh/design-system pull request #113
Opened 2023-07-26 10:07 UTC by Leotheluck

Inputs with clearable or passwords with masked were interactive if the input was disabled. This fix covers both cases, adds a specific cursor to the icons if the input is disabled and adds an e2e test to check if it works as intended.

2023-07-26 13:33 UTC, dpellier requested changes
<img width="558" alt="Capture d’écran 2023-07-26 à 15 32 53" src="https://github.com/ovh/design-system/assets/1390934/9d059e40-0616-4ba5-96f1-3ccc38e55e48">

`masked` seems to be broken on storybook

2023-07-26 14:13 UTC, astagnol approved these changes

2023-07-26 15:13 UTC, aesteves60 commented
Miss a test for the `hide` and spec test

2023-07-26 15:38 UTC, dpellier approved these changes

2023-07-27 08:14 UTC, aesteves60 approved these changes

2023-07-31 07:33 UTC, merged