docs(storybook): edit components links
ovh/design-system pull request #119
Opened 2023-07-28 11:45 UTC by feoche

2023-07-28 13:14 UTC, dpellier approved these changes

2023-07-28 14:13 UTC, astagnol requested changes
- Following links are not working on my side:
Icon, Accordion, Accordion group, Checkbox button, Link, Radio button, Tile, Toggle, Tooltip

- Password link sends to Form field component

2023-08-01 15:08 UTC, astagnol approved these changes

2023-08-02 07:49 UTC, aesteves60 approved these changes

2023-08-03 15:38 UTC, merged