docs(storybook): add versions selector in sidebar
ovh/design-system pull request #125
Opened 2023-08-01 12:51 UTC by feoche

2023-08-01 15:28 UTC, dpellier requested changes
(careful with your branch name, it should relates to the work done)

I don't see the version select on the deployed doc, is it normal?

2023-08-01 15:28 UTC, dpellier commented on packages/tools/storybook/.storybook/manager.js
> +    Object.entries(releases).map((value) => {
prefer `forEach` if you don't care about what is returned

2023-08-01 15:28 UTC, dpellier commented on packages/tools/storybook/.storybook/manager.js
> +}, 2000);
why do you need to wait here?

2023-08-01 15:28 UTC, dpellier commented on packages/tools/storybook/.storybook/manager.js
> +  const timer = setInterval(function(){
😧 is this really necessary?
can't you just add a dom loaded listener to start all your changes instead?

2023-08-07 08:21 UTC, feoche commented
Outdated by #133

2023-08-07 08:21 UTC, closed without merging