feat(popover): add new component popover
ovh/design-system pull request #14
Opened 2023-03-21 09:06 UTC by skhamvon

2023-03-21 09:10 UTC, ovh-cds commented
CDS Report build#124.0 ✘  
* 
  * build ✘

2023-03-22 08:57 UTC, ovh-cds commented
CDS Report build#128.0 ✘  
* 
  * build ✘

2023-03-22 16:14 UTC, ovh-cds commented
CDS Report build#133.0 ✘  
* 
  * build ✘

2023-03-23 15:07 UTC, ovh-cds commented
CDS Report build#140.0 ✘  
* 
  * build ✘

2023-03-23 16:20 UTC, ovh-cds commented
CDS Report build#142.0 ✘  
* 
  * build ✘

2023-03-23 16:28 UTC, ovh-cds commented
CDS Report build#143.0 ✘  
* 
  * build ✘

2023-03-24 16:02 UTC, ovh-cds commented
CDS Report build#159.0 ✘  
* 
  * build ✘

2023-03-24 16:29 UTC, ovh-cds commented
CDS Report build#164.0 ✘  
* 
  * build ✘

2023-03-28 15:57 UTC, ovh-cds commented
CDS Report build#178.0 ✘  
* 
  * build ✘

2023-03-29 15:05 UTC, ovh-cds commented
CDS Report build#185.0 ✘  
* 
  * build ✘

2023-03-29 16:35 UTC, ovh-cds commented
CDS Report build#187.0 ✘  
* 
  * build ✘

2023-03-30 15:15 UTC, ovh-cds commented
CDS Report build#189.0 ✘  
* 
  * build ✘

2023-03-30 16:10 UTC, ovh-cds commented
CDS Report build#191.0 ✘  
* 
  * build ✘

2023-03-30 16:25 UTC, ovh-cds commented
CDS Report build#192.0 ✘  
* 
  * build ✘

2023-04-03 10:53 UTC, ovh-cds commented
CDS Report build#196.0 ✘  
* 
  * build ✘

2023-04-11 08:42 UTC, ovh-cds commented
CDS Report build#220.0 ✘  
* 
  * build ✘

2023-04-11 09:37 UTC, ovh-cds commented
CDS Report build-storybook#221.0 ✘  
* 
  * build ✘

2023-04-11 09:50 UTC, ovh-cds commented
CDS Report build-storybook#221.1 ✘  
* 
  * build ✘

2023-04-11 14:41 UTC, ovh-cds commented
CDS Report build-storybook#222.0 ✘  
* 
  * build ✘

2023-04-11 16:13 UTC, ovh-cds commented
CDS Report build-storybook#224.0 ✘  
* 
  * build ✘

2023-04-12 08:07 UTC, ovh-cds commented
CDS Report build-storybook#224.1 ✘  
* 
  * build ✘

2023-04-21 10:14 UTC, astagnol requested changes

2023-04-21 10:14 UTC, astagnol commented on packages/design/assets/design-images/popover/popover-preview.png
Maybe we should update this png with current colors for typography

2023-04-21 10:14 UTC, astagnol commented on packages/stencil/components/popover/src/components/osds-popover-content/osds-popover-content.scss
> +:host {
Maybe we can cleaned unused css

2023-04-21 10:14 UTC, astagnol commented on packages/stencil/components/popover/src/components/osds-popover-content/osds-popover-content.tsx
> +  // Component properties as @Prop
to remove (from generator but no need to keep it there)

2023-04-21 10:14 UTC, astagnol commented on packages/stencil/components/popover/src/components/osds-popover/styles/osds-popover.color.scss
> +      //color: map_get($colors, color);
could be removed

2023-04-21 10:14 UTC, astagnol commented on packages/stencil/components/popover/src/components/osds-popover/styles/osds-popover.typography.scss
> +    //$typography-properties: ods-get-typography-properties(body, '400');
if not necessary, can be removed

2023-05-04 09:33 UTC, skhamvon commented on packages/libraries/core/src/components/popover/popover/ods-popover-controller.ts
> +  handleTriggerKey(event: KeyboardEvent): void {
As seen together, there is only button as trigger now, and it work with space and Enter

2023-05-04 09:46 UTC, skhamvon commented on packages/design/assets/design-images/popover/popover-preview.png
Updated

2023-05-04 10:09 UTC, ovh-cds commented
CDS Report build#391.0 ■   
* 
  * build ■

2023-05-04 10:09 UTC, ovh-cds commented
CDS Report build#391.0 ■   
* 
  * build ■

2023-05-04 10:36 UTC, ovh-cds commented
CDS Report build-storybook#392.0 ✘  
* 
  * build ✘

2023-05-04 14:42 UTC, ovh-cds commented
CDS Report build#394.0 ✘  
* 
  * build ✘

2023-05-04 14:42 UTC, ovh-cds commented
CDS Report build#393.0 ✘  
* 
  * build ✘

2023-05-04 15:38 UTC, ovh-cds commented
CDS Report build#399.0 ■   
* 
  * build ■

2023-05-04 15:38 UTC, ovh-cds commented
CDS Report build#399.0 ■   
* 
  * build ■

2023-05-05 08:14 UTC, ovh-cds commented
CDS Report build#405.0 ■   
* 
  * build ■

2023-05-05 08:14 UTC, ovh-cds commented
CDS Report build#405.0 ■   
* 
  * build ■

2023-05-09 13:49 UTC, ovh-cds commented
CDS Report build-storybook#424.0 ✘  
* 
  * build ✘

2023-05-16 14:41 UTC, skhamvon commented on packages/libraries/core/src/components/popover/popover-content/ods-popover-content-controller.ts
> +  validateAttributes(): void {
Removed

2023-06-23 15:20 UTC, ovh-cds commented
CDS Report build#764.0 ✘  
* 
  * build ✘

2023-06-26 12:27 UTC, ovh-cds commented
CDS Report build#775.0 ✘  
* 
  * build ✘

2023-06-26 13:43 UTC, dpellier requested changes
Regarding keyboard navigation, I couldn't focus the trigger on the storybook, so impossible to test Enter/Escape behavior

2023-06-26 13:43 UTC, dpellier commented on packages/libraries/core/jest.config.ts
> +console.log(config);
should be removed

2023-06-26 13:43 UTC, dpellier commented on packages/libraries/core/src/components/popover/popover/ods-popover-controller.ts
> +        this.component.surface.opened = false;
should use inner method `closeSurface`

2023-06-26 13:43 UTC, dpellier commented on packages/libraries/core/src/components/popover/popover/ods-popover-controller.ts
> +  checkForClickOutside(event: any): void {
can be removed ? should be managed by the surface

2023-06-26 13:43 UTC, dpellier commented on packages/libraries/core/src/components/popover/popover/ods-popover-controller.ts
> +  closeSurface(): void {
there is already one in the surface object

2023-06-27 12:23 UTC, dpellier approved these changes

2023-06-27 12:28 UTC, astagnol approved these changes

2023-06-27 12:30 UTC, merged