feat(menu): add menu on new archi
ovh/design-system pull request #141
Opened 2023-08-09 14:48 UTC by skhamvon

2023-08-09 15:15 UTC, ovh-cds commented
CDS Report build#1141.0 ■   
* 
  * build ■

2023-08-09 15:15 UTC, ovh-cds commented
CDS Report build#1141.0 ■   
* 
  * build ■

2023-08-09 15:18 UTC, ovh-cds commented
CDS Report build#1143.0 ✘  
* 
  * build ✘

2023-08-10 08:20 UTC, dpellier requested changes
build broken on CDS:
```
@ovhcloud/ods-storybook: ERR! resolve '@ovhcloud/ods-component-menu/docs/osds-menu/usage.mdx' in '/tmp/b0da275520918e23dd615e2a747528f1/run/packages/tools/storybook/stories/components/menu'
```

2023-08-10 08:20 UTC, dpellier commented on packages-new/components/menu/package.json
> +    "@ovhcloud/ods-component-divider": "^15.0.1"
button and divider are not dependencies, but devDependencies, they're used for dev purpose only (in the index.html), so remove both here

2023-08-10 08:20 UTC, dpellier commented on packages-new/components/menu/package.json
> +    "@ovhcloud/ods-common-testing": "^15.0.1",
and add here all the lib used for dev:
```
button
divider
icon
text
```

2023-08-10 08:20 UTC, dpellier commented on packages-new/components/menu/src/components/osds-menu-group/core/controller.ts
> +  constructor(component: OsdsMenuGroup) {
controller is empty, remove the whole file (and core directory)

2023-08-10 08:20 UTC, dpellier commented on packages-new/components/menu/src/components/osds-menu-group/osds-menu-group.tsx
> +  controller: OdsMenuGroupController = new OdsMenuGroupController(this);
remove

2023-08-10 08:20 UTC, dpellier commented on packages-new/components/menu/src/components/osds-menu-item/core/controller.ts
> +  protected component: OsdsMenuItem;
controller is empty, remove the whole file (and core directory)

2023-08-10 08:20 UTC, dpellier commented on packages-new/components/menu/src/components/osds-menu-item/osds-menu-item.tsx
> +  controller: OdsMenuItemController = new OdsMenuItemController(this);
remove

2023-08-10 08:20 UTC, dpellier commented on packages-new/components/menu/src/components/osds-menu-item/osds-menu-item.tsx
> +import { HTMLStencilElement } from '@stencil/core/internal';
use `import type { ...` for TS only code
(and move import type to the top of the imports)

2023-08-10 08:20 UTC, dpellier commented on packages-new/components/menu/src/components/osds-menu/core/controller.spec.ts
> +import { HTMLStencilElement } from '@stencil/core/internal';
`import type`

2023-08-10 08:20 UTC, dpellier commented on packages-new/components/menu/src/components/osds-menu/core/controller.spec.ts
> +} from '@ovhcloud/ods-testing/src';
`from '@ovhcloud/ods-common-testing';`

2023-08-10 08:20 UTC, dpellier commented on packages-new/components/menu/src/components/osds-menu/core/controller.spec.ts
> +class OdsMenuMock implements OdsMenu {
use extends instead and put only what is actually needed (see how other components are doing it)

2023-08-10 08:20 UTC, dpellier commented on packages-new/components/menu/src/components/osds-menu/core/controller.spec.ts
> +import { OdsMenuItem } from '../menu-item/ods-menu-item';
ko

2023-08-10 08:20 UTC, dpellier commented on packages-new/components/menu/src/components/osds-menu/interfaces/attributes.ts
> +interface OdsMenuAttributes {
It was not mention in the doc, but we try to keep object singular (and only array/list in plural), would be nice to update to `OdsMenuAttribute`

2023-08-10 08:20 UTC, dpellier commented on packages-new/components/menu/src/global.dev.ts
> +import '@ovhcloud/ods-component-link';
`link` doesn't seem to be used anymore

2023-08-10 08:20 UTC, dpellier commented on packages-new/components/menu/src/global.test.ts
> +import '@ovhcloud/ods-component-link';
same

2023-08-10 08:20 UTC, dpellier commented on packages-new/components/menu/src/global.dev.ts
> +  await customElements.whenDefined('osds-link');
same

2023-08-10 08:20 UTC, dpellier commented on packages-new/components/menu/src/index.ts
> +export * from './components/osds-menu/public-api';
export { OsdsMenu }

2023-08-10 08:20 UTC, dpellier commented on packages/tools/storybook/stories/components/menu/menu.specifications.stories.mdx
> +import Notes from '../notes.mdx';
unused, add to file or remove

2023-08-10 08:20 UTC, dpellier commented on packages/tools/storybook/stories/components/menu/menu.web-components.stories.ts
> +import { iframe } from '../../../.storybook/iframe';
remove

2023-08-10 08:20 UTC, dpellier commented on packages/tools/storybook/stories/components/menu/menu.web-components.stories.ts
> +import { config } from 'storybook-addon-xd-designs';
has been removed on another PR, remove them also (both xd)

2023-08-11 13:53 UTC, ovh-cds commented
CDS Report build#1174.0 ✘  
* 
  * build ✘

2023-08-16 08:32 UTC, dpellier requested changes

2023-08-16 08:32 UTC, dpellier commented on packages-new/components/menu/documentation/specifications/specifications-menu.mdx
> +import SpecsMessageContents from './specifications-menu-contents.mdx';
`SpecsMenuContents`

2023-08-16 08:32 UTC, dpellier commented on packages-new/components/menu/src/components/osds-menu-item/osds-menu-item.tsx
> +  @Element() el!: HTMLStencilElement;
probably not needed

2023-08-16 08:32 UTC, dpellier commented on packages-new/components/menu/src/components/osds-menu/core/controller.ts
> +import { OsdsMenu } from '../osds-menu';
type

2023-08-16 08:32 UTC, dpellier commented on packages-new/components/menu/src/components/osds-menu/osds-menu.e2e.ts
> +import type { OdsMenuAttribute } from './interfaces/attributes';
move type import on top

2023-08-16 08:32 UTC, dpellier commented on packages-new/components/menu/src/index.ts
> +export { OsdsMenu } from './components/osds-menu/public-api';
actually that`s the only `export *` we`ve kept for now, as filter is already made on public api file
plus you need to export all component here (see select for example)

2023-08-18 07:30 UTC, dpellier approved these changes

2023-08-18 07:30 UTC, merged