feat(modal): Overlay information component
ovh/design-system pull request #143
Opened 2023-08-09 16:37 UTC by Leotheluck

A Modal is used to provide some information to users that needs a response from them.

While a Modal is triggered, there is no interaction possible on the page that is overlaid so users have to dismiss or click on an action button to proceed further.

Modals are used in different cases:

    alerting users about something that requires their agreement
    confirming a user decision
    notifying the user of an important information

There are four different sub-types of standard Modals to inform users that a problem requires immediate response from them so the process can continue, depending on the usage:

    Error: reserved for errors, malfunctions, as well as critical issues
    Warning: reserved for Modals that need the user attention and acknowledgment but might not cause errors
    Information: provides information to users in context
    Success: reserved to provide a static persistent success information

They can be dismissible or not.

Usage:
`<osds-modal
    color="info"
    headline="On Vous Héberge ?"
    dismissible="true"
  >
    <osds-text color="text">
      OVHcloud, anciennement OVH, est une entreprise française. Elle pratique initialement de l'hébergement de serveur, et est un fournisseur d'accès à Internet (FAI), puis opérateur de télécommunications pour les entreprises. Elle se développe, à la fin des années 2010, dans le cloud computing (informatique en nuage).
    </osds-text>
    <osds-button slot="actions" color="default" href="https://www.ovh.com/fr/" target="_blank">En savoir plus</osds-button>
    <osds-button slot="actions" color="primary" href="https://www.ovh.com/fr/" target="_blank">On m'héberge</osds-button>
  </osds-modal>`

2023-08-10 09:16 UTC, dpellier requested changes
`inert` is not removed from body after closing the modal (tried on index.html)

The way it is implemented, how will it behave if you put multiple osds-modal accross an app?

2023-08-10 09:16 UTC, dpellier commented on packages/stencil/components/modal/src/components/osds-modal/osds-modal.scss
> +  display: flex;
probably not needed

2023-08-10 09:16 UTC, dpellier commented on packages/stencil/components/modal/src/components/osds-modal/osds-modal.tsx
> +                  {...{
same

2023-08-10 09:16 UTC, dpellier commented on packages/stencil/components/modal/src/components/osds-modal/styles/osds-modal.size.scss
> +    :host .wrapper .content .headline {
same as above regarding wrapped syntax

2023-08-10 09:16 UTC, dpellier commented on packages/stencil/components/modal/src/global.dev.ts
> +import '@ovhcloud/ods-stencil/components/button';
rebase and use new ones (careful to add dependencies accordingly)

2023-08-10 10:15 UTC, aesteves60 commented on packages/libraries/core/src/components/modal/ods-modal-controller.ts
> +  close() {
need spec test for the controller

2023-08-10 10:17 UTC, aesteves60 commented on packages/stencil/components/modal/src/docs/osds-modal/usage.mdx
> +<osds-modal>Modal</osds-modal>
Can you add a button trigger ?

2023-08-10 10:23 UTC, aesteves60 requested changes

2023-08-10 10:23 UTC, aesteves60 commented on packages/stencil/components/modal/src/components/osds-modal/osds-modal.tsx
> +              <osds-icon
We can't focus this "button" with navigation key. I think for this you need to wrap the icon with a circle button

2023-08-16 08:26 UTC, ovh-cds commented
CDS Report build#1183.0 ✘  
* 
  * build ✘

2023-08-17 09:55 UTC, dpellier requested changes
close button is bigger than the header, see
<img width="157" alt="Capture d’écran 2023-08-17 à 11 52 24" src="https://github.com/ovh/design-system/assets/1390934/35168a53-b99b-4efd-9c56-847403d9174d">
(more easy to see on click hold)

2023-08-17 16:06 UTC, feoche requested changes
- [x] Backdrop overlay should stay the same color, as --ods-color-primary-500 with 75% opacity
- [x] There are errors on events on Storybook story
- [x] The #root is `inert` in the story, so it can't be interacted with
- [x] Closing icon should be in size `sm`
- [x] Content padding should be `padding: var(--ods-size-06) var(--ods-size-08) var(--ods-size-08)`
- [x] Modal title margin-bottom should be `var(--ods-size-04)`
- [x] Modal actions margin-top should be `var(--ods-size-07)`
- [x] Wrapper width should behave like this, without media queries `max-width: clamp(36rem, 70%, 70%); min-width: 50%;`

2023-08-21 08:33 UTC, feoche requested changes
- [ ] Clicking on Storybook buttons causes errors `args.onOpenModal is not a function`
- [x] Main slot should have `overflow-y: auto`

2023-08-21 10:49 UTC, ovh-cds commented
CDS Report build#1224.0 ✘  
* 
  * build ✘

2023-08-24 06:50 UTC, dpellier requested changes

2023-08-24 06:50 UTC, dpellier commented on packages/libraries/core/src/components/public-api.ts
> +export * from './form-field/public-api';
form-field has been moved

2023-08-24 06:50 UTC, dpellier commented on packages/stencil/components/modal/src/components/osds-modal/osds-modal.tsx
> +  @Element() el!: HTMLElement;
probably not needed

2023-08-24 07:59 UTC, ovh-cds commented
CDS Report build#1269.0 ✘  
* 
  * build ✘

2023-08-24 10:05 UTC, dpellier approved these changes

2023-08-25 07:40 UTC, aesteves60 approved these changes

2023-08-25 07:40 UTC, feoche approved these changes

2023-08-25 07:40 UTC, merged