[DRAFT] feat(toggle): migrate to new archi
ovh/design-system pull request #151
Opened 2023-08-17 11:45 UTC by skhamvon

2023-08-17 12:09 UTC, ovh-cds commented
CDS Report build#1200.0 ✘  
* 
  * build ✘

2023-08-17 12:59 UTC, ovh-cds commented
CDS Report build#1204.0 ✘  
* 
  * build ✘

2023-08-18 07:43 UTC, dpellier requested changes

2023-08-18 07:43 UTC, dpellier commented on packages-new/components/toggle/src/components/osds-toggle/interfaces/attributes.ts
>  import { OdsThemeColorIntent } from '@ovhcloud/ods-theming';
type

2023-08-22 12:18 UTC, skhamvon commented on packages-new/components/toggle/src/components/osds-toggle/interfaces/attributes.ts
>  import { OdsThemeColorIntent } from '@ovhcloud/ods-theming';
Fixed

2023-08-22 12:49 UTC, dpellier approved these changes

2023-08-22 13:04 UTC, ovh-cds commented
CDS Report build-storybook#1246.0 ✘  
* 
  * build ✘

2023-08-23 06:57 UTC, merged