Refactor/file
ovh/design-system pull request #171
Opened 2023-08-28 12:10 UTC by aesteves60

2023-08-28 12:11 UTC, ovh-cds commented
CDS Report build#1304.0 ✘  
* 
  * build ✘

2023-08-29 12:17 UTC, feoche commented
- [ ] Should not have `cursor: pointer` on not-clickable areas
- [ ] Should have `cursor: move` when drag-and-drop 
- [ ] Inner link has error outline when File is in error state
- [ ] Storybook : when changing fields after File is in error state, component is emptied 
![image](https://github.com/ovh/design-system/assets/5332505/e80f8b43-4080-4314-9362-ae430c79a530)
- [ ] ^ Same with removing all files
- [ ] Should have min-width (344px)
- [ ] Storybook : not able to see File success state
- [ ] Storybook : Spec file does not work
- [ ] Max files alert should be displayed after uploading files (ex: with 4 files, add 2 files - 5th should be displayed, then after display error message)
- [ ] a11y : no action on Button/Links with Enter/Space

2023-08-29 12:33 UTC, dpellier requested changes

2023-08-29 12:33 UTC, dpellier commented on packages-new/components/file/src/components/osds-file-header/interfaces/attributes.ts
> +  disabled?: boolean;
almost in order ;)

2023-08-29 12:33 UTC, dpellier commented on packages-new/components/file/src/components/osds-file-item/core/controller.spec.ts
> +import { OdsFileItemAttribute } from '../interfaces/attributes';
type

2023-08-29 12:33 UTC, dpellier commented on packages-new/components/file/src/components/osds-file-item/core/controller.ts
> +    const result = Math.round(size / 1000);
Seems a bit too simple to render human readable size, especially on large files, you could use instead a formatter function like:
```
const byteSizes = ['B', 'KB', 'MB', 'GB', 'TB']; // put this on top outside of controller class

// controller method
function formatBytes(bytes, decimals = 0) {
  const k = 1024;
  const dm = decimals < 0 ? 0 : decimals:
  const i = Math.floor(Math.log(bytes) / Math.log(k));

  return `${parseFloat((bytes / (k ** i)).toFixed(dm))} {byteSizes[i]}`;
}
```

2023-08-29 12:33 UTC, dpellier commented on packages-new/components/file/src/components/osds-file-item/osds-file-item.tsx
> +        <span> ({this.getSizeInKiloBytes(this.size)} Ko)</span>
remove Ko and prefer a formatter function (see controller review)

2023-08-29 12:33 UTC, dpellier commented on packages-new/components/file/src/components/osds-file/osds-file.scss
> +}
I guess you can remove the empty hosts

2023-08-29 12:33 UTC, dpellier commented on packages-new/components/file/src/components/osds-file/osds-file.scss
> +@import 'styles/osds-file.typography';
you can remove those

2023-08-29 12:33 UTC, dpellier commented on packages-new/components/file/src/components/osds-file/public-api.ts
> +export { OsdsFile } from './osds-file'
export also interfaces (attr and events)

2023-08-29 12:33 UTC, dpellier commented on packages-new/components/file/stencil.config.ts
> +    excludeComponents: ['osds-icon', 'osds-link', 'osds-text']
regarding component dependencies, should be
`['osds-button', 'osds-icon', 'osds-link', 'osds-progress-bar']`

2023-11-24 10:29 UTC, closed without merging