feat(select): add slot selectedLabel
ovh/design-system pull request #197
Opened 2023-09-07 15:25 UTC by skhamvon

ODS-877
Add new slot to customize the label of an option once selected

2023-09-11 12:54 UTC, aesteves60 requested changes

2023-09-11 12:54 UTC, aesteves60 commented on packages/components/select/src/components/osds-select-option/osds-select-option.tsx
> +    } else {
no else need

2023-09-11 12:54 UTC, aesteves60 commented on packages/components/select/src/components/osds-select/osds-select.tsx
> +          <div class={'label'} innerHTML={ (value) ? this.selectedOptionLabel : undefined } >
I think we can inject javascript with the innerHTML

2023-09-11 12:54 UTC, aesteves60 commented on packages/components/select/src/components/osds-select/osds-select.tsx
> +          <div class={'label'} innerHTML={ (value) ? this.selectedOptionLabel : undefined } >
```suggestion
          <div class={'label'} innerHTML={ value ? this.selectedOptionLabel : undefined } >
```

2023-09-11 12:54 UTC, aesteves60 commented on packages/components/select/src/components/osds-select/osds-select.tsx
> +            { (value) ? undefined : <slot name={'placeholder'}>&nbsp;</slot> }
```suggestion
            { value ? undefined : <slot name={'placeholder'}>&nbsp;</slot> }
```

2023-09-18 11:55 UTC, dpellier approved these changes

2023-09-18 12:04 UTC, aesteves60 approved these changes

2023-09-18 12:15 UTC, astagnol approved these changes

2023-09-18 12:16 UTC, merged