feat(menu): add new component menu
ovh/design-system pull request #2
Opened 2023-02-28 16:10 UTC by skhamvon

2023-03-01 09:57 UTC, ovh-cds commented
CDS Report build#50.0 ✘  
* 
  * build ✘

2023-03-01 10:01 UTC, ovh-cds commented
CDS Report build#51.0 ✘  
* 
  * build ✘

2023-03-01 10:04 UTC, stevering commented
- [ ] you should update all import from `@ods/` to `@ovhcloud/ods-`

2023-03-01 13:50 UTC, ovh-cds commented
CDS Report build#56.0 ✘  
* 
  * build ✘

2023-03-06 15:58 UTC, ovh-cds commented
CDS Report build#64.0 ✘  
* 
  * build ✘

2023-03-08 14:50 UTC, ovh-cds commented
CDS Report build#74.0 ✘  
* 
  * build ✘

2023-03-09 08:58 UTC, ovh-cds commented
CDS Report build#78.0 ✘  
* 
  * build ✘

2023-03-09 10:03 UTC, ovh-cds commented
CDS Report build#79.1 ✘  
* 
  * build ✘

2023-03-13 15:10 UTC, ovh-cds commented
CDS Report build#86.0 ✘  
* 
  * build ✘

2023-03-14 14:36 UTC, ovh-cds commented
CDS Report build#89.0 ✘  
* 
  * build ✘

2023-03-14 15:26 UTC, ovh-cds commented
CDS Report build#91.0 ✘  
* 
  * build ✘

2023-03-15 14:07 UTC, ovh-cds commented
CDS Report build#91.1 ✘  
* 
  * build ✘

2023-03-16 10:59 UTC, ovh-cds commented
CDS Report build#102.0 ✘  
* 
  * build ✘

2023-03-16 13:55 UTC, ovh-cds commented
CDS Report build#106.0 ✘  
* 
  * build ✘

2023-03-27 10:33 UTC, ovh-cds commented
CDS Report build#174.0 ✘  
* 
  * build ✘

2023-03-27 14:18 UTC, ovh-cds commented
CDS Report build-storybook#175.0 ✘  
* 
  * build ✘

2023-03-27 14:24 UTC, ovh-cds commented
CDS Report build-storybook#176.0 ✘  
* 
  * build ✘

2023-04-21 08:07 UTC, ovh-cds commented
CDS Report build-storybook#256.0 ✘  
* 
  * build ✘

2023-04-21 09:10 UTC, ovh-cds commented
CDS Report build-storybook#256.1 ✘  
* 
  * build ✘

2023-07-27 09:50 UTC, feoche commented
- [ ] Loop focus on dropdown items with keyboard arrows 
> Test :
    * Navigate via keyboard onto the last Menu item
    * Press the `down arrow` key 
    * => Focused item should be now the first one
- [ ] Children Focus order kept after closing dropdown
> Test :
    * Navigate via keyboard onto the third Menu item without selecting it
    * Click outside of Menu
    * Return inside Menu items via tabulation
    * => Focused element is still third, it should fallback to first one as tabulated

2023-07-31 14:10 UTC, dpellier requested changes

2023-07-31 14:10 UTC, dpellier commented on packages/libraries/core/src/components/menu/menu/ods-menu-controller.spec.ts
> +        expect(component.surface.opened).toBeTruthy();
`toBe(true)`

2023-07-31 14:10 UTC, dpellier commented on packages/libraries/core/src/components/menu/menu/ods-menu-controller.spec.ts
> +        // await controller.handleKeyDown(event);
remove

2023-07-31 14:10 UTC, dpellier commented on packages/stencil/components/menu/src/components/osds-menu/osds-menu.tsx
> +    this.controller.propagateDisabledToChild(disabled);
maybe it would be easier to just watch the disabled prop, close the surface when true and avoid all this propagation stuff ?

2023-08-04 14:48 UTC, skhamvon commented on packages/libraries/core/src/components/menu/menu/ods-menu-controller.spec.ts
> +        expect(component.surface.opened).toBeTruthy();
done

2023-08-04 14:48 UTC, skhamvon commented on packages/libraries/core/src/components/menu/menu/ods-menu-controller.spec.ts
> +        expect(component.surface.opened).toBeTruthy();
done

2023-08-04 14:49 UTC, skhamvon commented on packages/libraries/core/src/components/menu/menu/ods-menu-controller.spec.ts
> +        expect(component.surface.opened).toBeTruthy();
done

2023-08-08 12:28 UTC, dpellier requested changes
Wrapper build seems still broken and files are missing on react and vue repo

Current result is:
<img width="202" alt="Capture d’écran 2023-08-08 à 14 26 10" src="https://github.com/ovh/design-system/assets/1390934/2f4481fd-aed3-443a-bcca-024dc6a1943e">

Expected result should be:
<img width="212" alt="Capture d’écran 2023-08-08 à 14 25 58" src="https://github.com/ovh/design-system/assets/1390934/715d54d6-e2e8-4d3b-a861-05e3e05b8d57">

2023-08-08 13:35 UTC, dpellier requested changes

2023-08-08 13:35 UTC, dpellier commented on packages-new/components/button/src/components/osds-button/styles/osds-button.size.scss
> +  padding: 0 var(--ods-size-squish-06-x);
why this change?
Updating default button style has impact on all other components using it, and thus should be planned carefully.

2023-08-08 13:52 UTC, ovh-cds commented
CDS Report build#1132.1 ✘  
* 
  * build ✘

2023-08-09 14:48 UTC, closed without merging