fix(button): submit button when in form
ovh/design-system pull request #21
Opened 2023-04-13 15:50 UTC by skhamvon

2023-04-13 16:26 UTC, ovh-cds commented
CDS Report build-storybook#236.0 ✘  
* 
  * build ✘

2023-04-14 13:40 UTC, ovh-cds commented
CDS Report build-storybook#238.0 ✘  
* 
  * build ✘

2023-04-17 08:37 UTC, ovh-cds commented
CDS Report build-storybook#239.0 ✘  
* 
  * build ✘

2023-04-25 08:12 UTC, stevering requested changes
this PR is started from master for a fix into release/12.0.
it is not the good workflow.
you have to start from release/12.0

2023-04-25 08:12 UTC, stevering commented on packages/contributing/contributing-deployment-and-versioning.mdx
> +Create a release branch from up-to-date `release/next` that corresponds to the version you are going to release like `release/X.Y`.
```suggestion
Create a release branch from up-to-date `master` that corresponds to the version you are going to release like `release/X.Y`.
```

2023-04-25 08:12 UTC, stevering commented on packages/contributing/contributing-deployment-and-versioning.mdx
> +You added breaking changes in the `release/next` branch:
```suggestion
You added breaking changes in the `master` branch:
```

2023-04-25 08:12 UTC, stevering commented on packages/contributing/contributing-deployment-and-versioning.mdx
> +Create a release branch from up-to-date `release/next` that corresponds to the version you are going to release like `release/X.Y`.
```suggestion
Create a release branch from up-to-date `master` that corresponds to the version you are going to release like `release/X.Y`.
```

2023-04-25 08:18 UTC, closed without merging