Refactor/stencil4
ovh/design-system pull request #210
Opened 2023-09-21 10:01 UTC by dpellier

- version update to Stencil v4
- remove already deprecated support of `custom-elements-bundle`
- simplify components stencil config
- simplify components globals
    - only one `globals.ts` file which contains only import of needed components (for local dev and test runners)
    - an optionnal `dev.ts` can be used if needed as a dev sandbox to test complex interaction
    - remove ods logger initialisation
- simplify components tsconfig (no more .dev, tsconfig.json is by default the dev version)
- run build action in parallel when possible to fasten global build time (on mac M1, went from 515s to 441s)

2023-09-21 10:12 UTC, ovh-cds commented
CDS Report build#1480.0 ✘  
* 
  * build ✘

2023-09-21 12:00 UTC, ovh-cds commented
CDS Report build#1480.1 ✘  
* 
  * build ✘

2023-09-21 12:07 UTC, aesteves60 requested changes

2023-09-21 12:07 UTC, aesteves60 commented on packages/components/spinner/stencil.config.ts
>  import { Config } from '@stencil/core';
Type or remove because the type is implicit

2023-09-21 12:12 UTC, ovh-cds commented
CDS Report build#1480.2 ✘  
* 
  * build ✘

2023-09-22 07:36 UTC, ovh-cds commented
CDS Report build#1485.0 ✘  
* 
  * build ✘

2023-09-22 09:35 UTC, ovh-cds commented
CDS Report build#1487.0 ✘  
* 
  * build ✘

2023-09-22 13:32 UTC, ovh-cds commented
CDS Report build#1489.0 ✘  
* 
  * build ✘

2023-09-22 14:41 UTC, ovh-cds commented
CDS Report build#1490.0 ✘  
* 
  * build ✘

2023-09-25 07:20 UTC, aesteves60 requested changes

2023-09-25 07:20 UTC, aesteves60 commented on packages/components/breadcrumb/stencil.config.ts
> +console.log(getStencilConfig({
oups

2023-09-25 07:28 UTC, closed without merging