fix(phone-number): style select + clear input error + sort list select options
ovh/design-system pull request #215
Opened 2023-09-26 12:01 UTC by aesteves60

- Style
- select sort
- filter country not supported by the `google-libphonenumber`
-

2023-09-26 12:35 UTC, dpellier requested changes

2023-09-26 12:35 UTC, dpellier commented on packages/components/phone-number/src/components/osds-phone-number/osds-phone-number.scss
> +    --ods-size-select-surface-width: calc(#{$phone-number-input-width} + 71px);
those are 2 hardcoded value, no need for `calc`

2023-09-26 12:35 UTC, dpellier commented on packages/components/phone-number/src/components/osds-phone-number/osds-phone-number.tsx
> +            { this.parsedCountries?.sort((a, b) => this.sortCountriesByName(a, b)).map((country) => {
using the sort directly in the render will go through it on every render, would be better to sort on Watch handler to ensure we sort only once

2023-09-27 08:30 UTC, manoncarbonnel approved these changes

2023-09-27 09:57 UTC, dpellier approved these changes

2023-09-27 11:59 UTC, merged

2023-09-27 11:59 UTC, astagnol approved these changes