Feat/datagrid step 4
ovh/design-system pull request #241
Opened 2023-10-16 07:52 UTC by aesteves60

2023-10-16 08:02 UTC, dpellier requested changes

2023-10-16 08:02 UTC, dpellier commented on packages/components/datagrid/src/components/osds-datagrid/core/controller.ts
> +            formatter: (cell: CellComponent) => column.formatter?.(cell.getValue()) ?? this.getOdsText(cell.getValue(), ODS_TEXT_SIZE._400),
would be nice to add a dedicated sandbox page with a very large datagrid (10000+ rows) to ensure we don't have any perf issue

2023-10-16 09:53 UTC, dpellier requested changes
Also add a `build:ci` command on datagrid package otherwise doc will not be build

2023-10-19 07:56 UTC, dpellier requested changes
Cursor is always `pointer` on each row, should be default one until row get interactive (like draggable)

2023-10-19 12:12 UTC, feoche requested changes
UI review : 
- [x] In "Default" Storybook story, `rowHeight` property should be 52px (3.25rem)
- [x] Changing story parameters does not trigger component re-render
- [x] Cursor should be `auto` when hovering rows
- [ ] [Safari] column with icon is 1px off at the bottom of each cell (can be fixed with --webkit-inline-flex on row)
- [x] Sortable column label height is different to non-sortable label
- [x] Header row has different height than the `rowHeight` (to be discussed)

- [x] (Switching stories between "Default" and "Large Data" breaks its display - hard to reproduce)
- [x] Remove control on Large Data Page

2023-10-24 12:46 UTC, Leotheluck approved these changes

2023-10-24 15:41 UTC, astagnol requested changes
Click on isSelectable control, then click again. Header is broken:
![Capture d’écran 2023-10-24 à 17 40 54](https://github.com/ovh/design-system/assets/53512103/10e2d482-8afe-468b-b012-e1db2bc5322e)

2023-10-25 08:55 UTC, feoche commented
- [ ] Removing all columns does not get the "noResultLabel" to appear
- [ ] Header is always as "fixed", without a drop shadow (to discuss with Design)

2023-10-26 07:53 UTC, astagnol approved these changes

2023-10-26 08:09 UTC, feoche approved these changes

2023-10-26 08:40 UTC, merged