Feat/eslint
ovh/design-system pull request #244
Opened 2023-10-17 13:04 UTC by manoncarbonnel

:rotating_light: Added [linter](https://eslint.org/) for `.js` `.ts` and `.tsx` files with config:

- script at root and in each component `package.json`
- html report artifact
- specified rules (according to the team's provided code guidelines)
- ignored folders containing generated files or documentation

I also fixed the errors for the **text component**.

2023-10-18 09:00 UTC, dpellier requested changes
After discussion with the team, can you change the rule to ensure space before inline bracket:
```
// OK
import { DEFAULT_ATTRIBUTE } from './constants/default-attributes';

// KO
import {DEFAULT_ATTRIBUTE} from './constants/default-attributes';
```

2023-10-18 09:15 UTC, dpellier requested changes
Running `yarn build:prod` locally on the examples projects fails due to eslint issues.
Do you reproduce the issue?
If so, `build:prod` is not supposed not fails due to eslint issues, can you have a look and fix it?

2023-10-24 12:11 UTC, dpellier requested changes

2023-10-24 12:11 UTC, dpellier commented on package.json
> +    "eslint-plugin-import": "^2.29.0",
no `^`

2023-10-25 07:29 UTC, dpellier requested changes

2023-10-25 07:29 UTC, dpellier commented on package.json
> +    "eslint-import-resolver-typescript": "^3.6.1",
nop

2023-10-25 07:31 UTC, dpellier commented on packages/components/text/src/components/osds-text/constants/default-attributes.ts
> +import type { OdsTextAttribute } from '../interfaces/attributes';
would be nice to have type on top

2023-10-25 07:33 UTC, dpellier commented on packages/components/text/src/components/osds-text/osds-text.tsx
> +
space?

2023-10-26 08:04 UTC, dpellier approved these changes

2023-10-26 08:42 UTC, aesteves60 approved these changes

2023-10-26 09:28 UTC, merged