Feat/datagrid step5
ovh/design-system pull request #246
Opened 2023-10-19 12:22 UTC by aesteves60

Add hideableColumns attributes
Add last columns for selection of the visible column
![image](https://github.com/ovh/design-system/assets/27487948/9ece1a18-1307-495a-8e6b-617e04c74cde)

2023-10-25 08:59 UTC, feoche requested changes
UI review :
- [ ] Removing all columns in filter makes the Datagrid appear in a strange way 
![image](https://github.com/ovh/design-system/assets/5332505/616b0a07-bbbb-4bd6-9d31-7eff87c8279f)

2023-10-25 12:23 UTC, astagnol requested changes
UI:
Since checkbox in popover should be 16px, checkbox displayed when isSelectable is set to true should 16px too (instead of 20)

2023-10-25 12:23 UTC, astagnol commented on packages/components/datagrid/src/components/osds-datagrid/core/controller.ts
>                  <osds-checkbox-button color="${ODS_THEME_COLOR_INTENT.primary}">
osds-checkbox-button must be size sm (16px)

2023-10-30 14:45 UTC, feoche approved these changes

2023-10-30 15:22 UTC, manoncarbonnel commented on packages/components/datagrid/src/components/osds-datagrid/osds-datagrid.e2e.ts
> +    expect(columns?.[2]).toBe(undefined);
**nitpick**: this expect does not seem relevant to me because of line 191

2023-10-30 16:22 UTC, aesteves60 commented on packages/components/datagrid/src/components/osds-datagrid/osds-datagrid.scss
>              height: unset !important;
I can't the lib place the height directly on the style

2023-10-31 07:43 UTC, merged