Refactor/stencil4
ovh/design-system pull request #247
Opened 2023-10-23 07:19 UTC by dpellier

- version update to Stencil v4
- remove already deprecated support of custom-elements-bundle
- simplify components stencil config
- simplify components globals
    - only one globals.ts file which contains only import of needed components (for local dev and test runners)
    - an optionnal dev.ts can be used if needed as a dev sandbox to test complex interaction
    - remove ods logger initialisation
- simplify components tsconfig (no more .dev, tsconfig.json is by default the dev version)
- components build using a script to workaround Stencil strange types generation issue

2023-10-23 08:48 UTC, aesteves60 requested changes

2023-10-23 08:48 UTC, aesteves60 commented on packages/components/radio/package.json
> -    "doc:radio-group": "typedoc src/components/osds-radio-group/public-api.ts --out ./docs-api/radio-group --json ./docs-api/radio-group/typedoc.json",
idem with this script

2023-10-24 07:34 UTC, aesteves60 approved these changes

2023-10-24 12:30 UTC, Leotheluck approved these changes

2023-10-24 15:17 UTC, astagnol approved these changes

2023-10-24 15:19 UTC, merged