refactor(icon): style to BEM & 1 scss file
ovh/design-system pull request #250
Opened 2023-10-23 14:54 UTC by aesteves60

2023-10-23 15:12 UTC, dpellier requested changes

2023-10-23 15:12 UTC, dpellier commented on packages/components/icon/src/components/osds-icon/osds-icon.tsx
>        <Host {...{
can you also remove the destructuring when not necessary ?

2023-10-24 12:07 UTC, dpellier approved these changes

2023-10-24 12:24 UTC, Leotheluck approved these changes

2023-10-24 12:33 UTC, merged