feat/doc UI cmpt improv
ovh/design-system pull request #262
Opened 2023-10-31 13:36 UTC by astagnol

2023-11-02 08:47 UTC, dpellier requested changes
Why are you naming the file in each stories `1_<compo>.specifications.stories.mdx`?
Files are already in a compo dir, you can just have specifications.stories.mdx on each

WDYT about having all the component categories open on first load?
Would be easier for the user to get a quick overview of all the list

2023-11-02 08:47 UTC, dpellier commented on packages/storybook/.storybook/preview.js
> +      hidden: true
can't you just remove them ?

2023-11-03 09:09 UTC, aesteves60 approved these changes

2023-11-06 16:14 UTC, dpellier requested changes
I can't click on the version select
<img width="171" alt="Capture d’écran 2023-11-06 à 17 14 36" src="https://github.com/ovh/design-system/assets/1390934/f992190b-25a9-4bc1-8f19-b05b29d92302">

2023-11-06 16:14 UTC, dpellier commented on packages/storybook/.storybook/manager.js
> +            releaseSelectorConfig.enabled = false;
`disconnect` should be enough, you get the observer as second args on the callback function.
```
const callback = function(mutationsList, observer) {
  ...
  observer.disconnect();
}
```

2023-11-06 16:14 UTC, dpellier commented on packages/storybook/.storybook/manager.js
> +            itemsObserverConfig.enabled = false;
same

2023-11-07 10:35 UTC, dpellier requested changes

2023-11-07 10:35 UTC, dpellier commented on packages/storybook/.storybook/manager.js
> -            itemsObserverConfig.enabled = false;
then remove also the const declaration and their usage in the if

2023-11-07 13:06 UTC, dpellier approved these changes

2023-11-07 13:21 UTC, merged