Feat/step 2 doc
ovh/design-system pull request #286
Opened 2023-11-17 14:37 UTC by astagnol

2023-11-20 08:58 UTC, aesteves60 requested changes

2023-11-20 08:58 UTC, aesteves60 commented on packages/storybook/stories/ovhcloud-design-system/get-started.stories.mdx
> +- `@import { applyPolyfills, defineCustomElements } '@ovhcloud/ods-stencil/components/loader/';`
Old package

2023-11-20 08:58 UTC, aesteves60 commented on packages/storybook/stories/ovhcloud-design-system/get-started.stories.mdx
> +  import { defineCustomElements, applyPolyfills } from './node_modules/@ovhcloud/ods-stencil/components/loader';
Old package

2023-11-21 08:44 UTC, aesteves60 approved these changes

2023-11-22 09:01 UTC, Leotheluck approved these changes

2023-11-23 08:45 UTC, merged