fix(datagrid): row change & storybook
ovh/design-system pull request #288
Opened 2023-11-21 16:45 UTC by aesteves60

Error on row change: test throx when the fix was not present
Phone-number / Search-bar select cropped

2023-11-22 09:30 UTC, astagnol requested changes
Datagrid is not displayed as expected in usage guidelines when using a Menu with row formatter:
![Capture d’écran 2023-11-22 à 10 08 50](https://github.com/ovh/design-system/assets/53512103/48864588-cbfa-40ee-ad7d-a3dbfe1f6283)

It seems there is still a regression from v16.2.1 (Select):
![Capture d’écran 2023-11-22 à 10 21 05](https://github.com/ovh/design-system/assets/53512103/64780284-3481-458b-8bc2-4636f65f266d)
Not sure this regression is related to Datagrid though. We can discuss about it

2023-11-24 08:49 UTC, feoche approved these changes

2023-11-24 08:50 UTC, astagnol approved these changes

2023-11-24 09:41 UTC, Leotheluck approved these changes

2023-11-24 10:28 UTC, merged