fix(modal): switch to dialog element
ovh/design-system pull request #290
Opened 2023-11-22 15:46 UTC by Leotheluck

- `OsdsModal` is now using a `HTMLDialogElement` and is no longer appended to the body. (_fixes react children problem)_
- `OsdsModal` is now reactive to `Escape` key. _(will close the modal if dismissible)_
- `OsdsModal`'s icon has been fixed and no longer features a colored background.
- Tests have been added to check if focus is well applied.

2023-11-22 16:12 UTC, aesteves60 requested changes

2023-11-22 16:12 UTC, aesteves60 commented on packages/components/modal/src/components/osds-modal/osds-modal.spec.ts
> +    instance.modal = {
Is it work ?

2023-11-22 16:12 UTC, aesteves60 commented on packages/components/modal/src/components/osds-modal/osds-modal.tsx
> +  render(): void {
return JSX.Element

2023-11-22 16:12 UTC, aesteves60 commented on packages/components/modal/src/components/osds-modal/osds-modal.tsx
> +              <osds-button onClick={(): Promise<void> => this.close()} color={color} circle variant='ghost'>
Use enum for variant

2023-11-22 16:12 UTC, aesteves60 commented on packages/components/modal/src/components/osds-modal/styles/osds-modal.color.scss
> +    .wrapper::backdrop {
use the scss syntaxe .wrapper { &::backdrop { } }

2023-11-23 13:04 UTC, aesteves60 approved these changes

2023-11-23 15:02 UTC, skhamvon approved these changes

2023-11-24 08:52 UTC, astagnol approved these changes

2023-11-24 10:28 UTC, merged