Refactor/input evnts
ovh/design-system pull request #314
Opened 2023-12-12 09:23 UTC by skhamvon

2023-12-27 16:51 UTC, aesteves60 requested changes
Need to add the event odsReset, odsClear and odsHide

2023-12-27 16:51 UTC, aesteves60 commented on packages/common/core/src/form/interfaces/events.ts
> +interface OdsCommonFieldValueChangeEventDetail {
We need the name of the field too

2023-12-27 16:51 UTC, aesteves60 commented on packages/components/src/input/src/components/osds-input/interfaces/events.ts
> +interface OdsInputEvent extends OdsCommonFieldEvent {
Don't rewrite the `odsBlur`, `odsFocus` & `odsValueChange`

2023-12-28 15:57 UTC, skhamvon commented on packages/common/core/src/form/interfaces/events.ts
> +interface OdsCommonFieldValueChangeEventDetail {
added

2023-12-29 10:04 UTC, aesteves60 approved these changes

2024-01-04 13:30 UTC, merged