feat(input): add form associated
ovh/design-system pull request #321
Opened 2023-12-18 13:39 UTC by aesteves60

Add form associated on `input` component
Update to stencil 4.8.2 for the callback `formResetCallback`
Update `button` for support type reset

2023-12-18 13:58 UTC, dpellier requested changes

2023-12-18 13:58 UTC, dpellier commented on packages/components/input/package.json
> +    "@ovhcloud/ods-component-button": "16.5.0",
no needed anymore with the new arch, you can skip it already :)

2023-12-18 13:58 UTC, dpellier commented on packages/components/input/src/index.html
> -  <osds-input inline type="text" value="On Vous Héberge ?" disabled clearable></osds-input>
Can you keep some test of input outside of a <form> element to ensure they can still be used?

2023-12-19 08:48 UTC, dpellier approved these changes

2023-12-19 09:03 UTC, astagnol approved these changes

2023-12-21 16:52 UTC, closed without merging