fix(datagrid): overflowing elements
ovh/design-system pull request #326
Opened 2023-12-20 09:43 UTC by Leotheluck

Simple fix to solve the problem of the `OsdsDatagrid` cells overflowing on the other ones without compromising the surface's ability to overflow on custom components.

2023-12-21 16:46 UTC, dpellier requested changes

2023-12-21 16:46 UTC, dpellier commented on packages/components/src/datagrid/src/index.html
> +      { title: "First name", field: "firstname", overflow: true, formatter: (cellValue, rowValue) => {
to remove

2023-12-21 16:46 UTC, dpellier commented
Maybe add some doc on usage to explain how to put a csutom overflowing element (add position absolute)?

2023-12-21 16:57 UTC, dpellier commented on packages/components/src/datagrid/src/components/osds-datagrid/osds-datagrid.scss
> +            osds-menu,
probably better not to have a specific "magic" behavior for some ods component.

2023-12-22 08:56 UTC, aesteves60 approved these changes

2023-12-26 09:13 UTC, dpellier approved these changes

2023-12-26 09:34 UTC, merged