Feat/select form
ovh/design-system pull request #335
Opened 2024-01-08 14:29 UTC by aesteves60

Add common method, attributes, event & form associated

2024-01-09 16:10 UTC, dpellier commented on packages/components/src/select/src/components/osds-select/interfaces/attributes.ts
>    inline: boolean;
is there any field without `inline` option?

2024-01-25 15:55 UTC, dpellier requested changes

2024-01-25 15:58 UTC, aesteves60 commented on packages/components/src/select/src/components/osds-select-group/osds-select-group.tsx
> +        size: 'md',
It's for the style

2024-01-26 15:57 UTC, dpellier approved these changes

2024-01-29 09:23 UTC, merged