fix(modal): prevent scroll when modal is open
ovh/design-system pull request #337
Opened 2024-01-10 14:37 UTC by skhamvon

Prevent scroll when modal is opened

2024-01-12 08:14 UTC, dpellier requested changes
I'm a bit concern about deleting property of inetgrator element, it could have set the overflow value on purpose and we shouldn't remove it.
Can you try to add this behaviour through an ODS named class instead?

2024-01-12 13:25 UTC, aesteves60 approved these changes

2024-01-12 15:00 UTC, dpellier requested changes
does not work on storybook
<img width="717" alt="Capture d’écran 2024-01-12 à 16 00 14" src="https://github.com/ovh/design-system/assets/1390934/cc1f1cfb-1961-4d28-9de6-77e9105875ed">

2024-01-16 16:32 UTC, dpellier requested changes
Ok initial render seems okay, but there is another issue regarding scrolling, the modal is positionned relatively of its trigger, if the trigger is scrolled, the modal deos not open centered.
To reproduce:
- go to the storybook modal page
- close the modal
- inspect the sandbox and add a long height to one of the container (ex: `<div id="root">`
- scroll to put the trigger button on the very top edge of the page
- click on the button
- the modal appear on the top edge, and partially hidden

2024-01-18 08:10 UTC, merged