fix(pagination): Component goes out of bounds
ovh/design-system pull request #338
Opened 2024-01-10 17:25 UTC by Leotheluck

**Bug Description:** Pagination - Goes out of bounds _[Chromium, Safari]_

**Steps to verify:** 
1) Open `OsdsPagination` component on `Chromium` or `Safari`.
2) Click on disabled `previous` arrow or `next` arrow.
3) The component should not go out of bounds anymore.

2024-01-11 08:26 UTC, dpellier reviewed
if you did fix all the lint, can you please rename the `FIXME_lint:ts` to `lint:ts` in the `package.json`

2024-01-11 09:05 UTC, dpellier requested changes
please add two e2e test that validate that clicks are not enabled when on far right/left

2024-01-11 14:35 UTC, dpellier requested changes

2024-01-11 14:35 UTC, dpellier commented on packages/components/src/pagination/src/components/osds-pagination/osds-pagination.e2e.ts
> +      expect(current).toEqual(1);
use `toBe` when testing primitive values

2024-01-12 13:23 UTC, aesteves60 approved these changes

2024-01-12 14:58 UTC, dpellier approved these changes

2024-01-12 14:58 UTC, merged