feat(pagination): add defaultItemsPerPage attribute
ovh/design-system pull request #354
Opened 2024-01-23 08:31 UTC by Leotheluck

This new feature will allow the users to select the default number of items displayed per page in the `OsdsPagination` component.

Content:
- Added new attribute `defaultItemsPerPage` to `OsdsPagination`.
- Added new type `ODS_PAGINATION_PER_PAGE`.

To review:
Check if you are able to add a `defaultItemsPerPage` attribute to your `OsdsPagination` component, and if it applies correctly.

2024-01-23 09:15 UTC, dpellier requested changes

2024-01-23 09:15 UTC, dpellier commented on packages/components/src/pagination/src/components/osds-pagination/constants/pagination-per-page.ts
> +type ODS_PAGINATION_PER_PAGE = typeof ODS_PAGINATION_PER_PAGE_OPTIONS[number];
better to transform the above as an enum (like other constants in the project)

2024-01-23 09:15 UTC, dpellier commented on packages/components/src/pagination/src/components/osds-pagination/osds-pagination.tsx
> +  @State() itemPerPage = this.defaultItemsPerPage ? this.defaultItemsPerPage : ODS_PAGINATION_PER_PAGE_MIN;
`= this.defaultItemsPerPage || ODS_PAGINATION_PER_PAGE_MIN;` ?

2024-01-23 10:11 UTC, astagnol requested changes
- New attribute `defaultItemsPerPage` is not displayed in Storybook Specifications
- We should add that new attribute to controls in Storybook (Total Items page)
- Please add an integration example for this attribute to Usage Guidelines

2024-01-25 08:14 UTC, dpellier requested changes
seems KO on demo page
<img width="1200" alt="Capture d’écran 2024-01-25 à 09 13 38" src="https://github.com/ovh/design-system/assets/1390934/34dc5d1d-a221-4598-86ad-fb58cf6124e8">

2024-01-29 09:16 UTC, dpellier requested changes
New issue dtected on storybook.
As the `defaultItemsPerPage` control field is a number input, we can put a value that is not handled by the component (ex: set 26 and reload => empty select)

2 thing to do here:
- manage this edge case on component side to default to min value if the value set is incorrect (+ tests)
- update the story page with a select control instead
```
control: 'select',
options: ODS_PAGINATION_PER_PAGE_OPTIONS,
```

2024-01-31 08:19 UTC, dpellier approved these changes

2024-02-01 09:56 UTC, astagnol requested changes

2024-02-01 09:56 UTC, astagnol commented on packages/components/src/pagination/documentation/usage-guidelines/usage.mdx
>  ### Total Items
I think we should mention "Default items per page"here in the title with "Total items" since they work together

2024-02-01 09:56 UTC, astagnol commented on packages/storybook/stories/components/pagination/3_demo.stories.ts
When I pick up an option from defaultItemsPerPage select in Controls, it does not apply to the component in the Story. 
For example, I've set total items  to '100' and picked up '100' from defaultItemsPerPage select. Nothing happens until I refresh the page

2024-02-01 10:40 UTC, dpellier commented on packages/storybook/stories/components/pagination/3_demo.stories.ts
default-like props are used only on initial render, so if you change the value, you'll have to reload to see the change.

2024-02-01 13:40 UTC, astagnol commented on packages/storybook/stories/components/pagination/3_demo.stories.ts
Alright, thanks. 
Then, I take note that maybe I should specify this in the control description so our users won't be surprised

2024-02-01 13:40 UTC, astagnol approved these changes

2024-02-02 14:59 UTC, merged