fix(disabled): fix components
ovh/design-system pull request #356
Opened 2024-01-23 15:11 UTC by manoncarbonnel

Fixed disabled components by : 
- preventing event propagation manually if disabled prop is set to `true`.
- both on click and keydown events.

To reproduce : check your console when clicking on a disabled component
- on Storybook's component story
- using `yarn start` in a component folder

2024-01-23 15:16 UTC, aesteves60 requested changes
Need test for all the component

2024-01-23 15:16 UTC, aesteves60 commented on packages/components/src/tile/src/components/osds-tile/core/controller.ts
> +      this.logger.log('[tile]', 'clicked');
Remoev the function it's useless

2024-01-24 08:19 UTC, dpellier requested changes

2024-01-24 08:19 UTC, dpellier commented on packages/components/src/checkbox/src/components/osds-checkbox/osds-checkbox.tsx
> +      this.logger.log(`[checkbox=${this.inputId}]`, 'click');
you can remove the logger

2024-01-24 08:19 UTC, dpellier commented on packages/components/src/checkbox/src/components/osds-checkbox/osds-checkbox.tsx
> +      this.logger.log(`[checkbox=${this.inputId}]`, 'key event', { event });
you can remove the logger

2024-01-24 16:13 UTC, dpellier requested changes
Please redo your last commit without all the formatting changes

2024-01-30 13:19 UTC, dpellier requested changes

2024-01-30 13:19 UTC, dpellier commented on packages/components/src/checkbox/src/components/osds-checkbox/core/ods-checkbox-controller.ts
> +      this.logger.log(`[checkbox=${this.component.value}]`, 'click event', { event });
remove logger

2024-01-31 14:33 UTC, dpellier requested changes
radio is still clickable:
- go to doc -> radio -> Demo -> Default
- check disabled
- open console
- click on item
- log click

2024-01-31 15:31 UTC, dpellier requested changes

2024-01-31 15:31 UTC, dpellier commented on packages/components/src/radio/src/components/osds-radio/core/controller.ts
> +    if (!this.component.disabled) {
missing e2e related test

2024-02-07 08:46 UTC, aesteves60 approved these changes

2024-02-08 16:39 UTC, merged