fix(radio-group): fix log error in storybook
ovh/design-system pull request #357
Opened 2024-01-25 10:07 UTC by skhamvon

Fix console log in storybook for Update strategy Demo of Radio Group

2024-01-25 10:36 UTC, dpellier requested changes
Still logger error on `Radio Button` demo page

2024-01-25 13:25 UTC, dpellier approved these changes

2024-01-26 09:06 UTC, aesteves60 approved these changes

2024-01-26 09:08 UTC, aesteves60 approved these changes

2024-01-26 09:35 UTC, merged