fix(pagination): hide navigation when totalitems lower itemsPerPage
ovh/design-system pull request #376
Opened 2024-02-14 14:28 UTC by skhamvon

Hide navigation of pagination when totalItems is lower than itemsPerPage

2024-02-15 08:57 UTC, manoncarbonnel approved these changes

2024-02-15 09:19 UTC, dpellier requested changes
waiting for spec update, there are some weird behavior because of the select values

2024-02-15 10:50 UTC, aesteves60 approved these changes

2024-02-20 09:26 UTC, dpellier requested changes
Select should be visible all the time
<img width="232" alt="Capture d’écran 2024-02-20 à 10 25 28" src="https://github.com/ovh/design-system/assets/1390934/3c5a16f1-f3b5-4168-a347-86c3a07c7cd4">
<img width="308" alt="Capture d’écran 2024-02-20 à 10 25 34" src="https://github.com/ovh/design-system/assets/1390934/a5595cd9-64bd-4bf2-9026-191454ed9b3f">

2024-02-20 15:24 UTC, astagnol requested changes
![Capture d’écran 2024-02-20 à 16 23 18](https://github.com/ovh/design-system/assets/53512103/8726c1cb-66d5-4e38-b3c6-b71f9680eafd)

Arrows and one page (1) buttons should be displayed when page amount is less than 2

2024-02-21 10:10 UTC, dpellier approved these changes

2024-02-26 11:23 UTC, astagnol approved these changes

2024-02-26 15:47 UTC, merged