fix(datepicker): surface border color in error
ovh/design-system pull request #380
Opened 2024-02-15 14:23 UTC by skhamvon

Fix border color of datepicker surface when component is in error

2024-02-19 08:52 UTC, dpellier requested changes
broken on Safari

<img width="329" alt="Capture d’écran 2024-02-19 à 09 51 54" src="https://github.com/ovh/design-system/assets/1390934/d0f13de2-0092-4218-8bc2-722e075fcf7f">

2024-02-21 16:56 UTC, aesteves60 approved these changes

2024-02-22 08:04 UTC, dpellier approved these changes

2024-02-22 08:56 UTC, astagnol approved these changes

2024-02-22 10:06 UTC, merged