fix(input): handler kay space on icon button
ovh/design-system pull request #382
Opened 2024-02-16 10:23 UTC by aesteves60

2024-02-19 09:02 UTC, dpellier approved these changes

2024-02-19 13:50 UTC, astagnol requested changes
- On Safari v16.6, cannot focus on the Icon button
- On Safari v17, can focus on the Icon button but no style is applied (no border like on firefox)

2024-02-20 13:37 UTC, aesteves60 commented
In BrowserStack, it's focusable with the good design in safari 16.5 & 17.3.
I can't try on 16.6

2024-02-20 15:28 UTC, astagnol approved these changes

2024-02-21 08:41 UTC, merged