feat(table): initial commit
ovh/design-system pull request #387
Opened 2024-02-22 23:55 UTC by manoncarbonnel

Added a new table component with its tests and accessibility recommendations guidelines in its documentation.

2024-02-23 11:02 UTC, astagnol requested changes
- please create storybook files for the component (it would have been created by using the generator)
- some comments refer to the Chip instead of Table
- as I understand why it could be nice to have recommendations in Usage Guidelines, this comes from the Zeroheight and I'm not sure we should duplicate it. We need to discuss a bit about this

2024-02-23 14:42 UTC, aesteves60 requested changes

2024-02-23 14:42 UTC, aesteves60 commented on packages/components/src/table/src/components/osds-table/core/controller.ts
> + * common controller logic for chip component used by the different implementations.
Remove comment

2024-02-23 14:42 UTC, aesteves60 commented on packages/components/src/table/src/components/osds-table/core/controller.ts
> +      this.logger.warn('The size attribute must be set');
Use console.warn and in the test spy it (everywhere)

2024-02-23 14:42 UTC, aesteves60 commented on packages/components/src/table/src/components/osds-table/osds-table.e2e.screenshot.ts
> +        <osds-table size='sm''></osds-table>
```suggestion
        <osds-table size='sm'></osds-table>
```

2024-02-23 14:42 UTC, aesteves60 commented on packages/components/src/table/src/components/osds-table/osds-table.e2e.screenshot.ts
> +        <osds-table size='md''></osds-table>
```suggestion
        <osds-table size='md'></osds-table>
```

2024-02-23 14:42 UTC, aesteves60 commented on packages/components/src/table/src/components/osds-table/osds-table.e2e.screenshot.ts
> +        <osds-table size='lg''></osds-table>
```suggestion
        <osds-table size='lg'></osds-table>
```

2024-02-23 14:42 UTC, aesteves60 commented on packages/components/src/table/src/components/osds-table/osds-table.e2e.screenshot.ts
> +        <osds-table size='striped''></osds-table>
```suggestion
        <osds-table size='striped'></osds-table>
```

2024-02-27 14:31 UTC, astagnol requested changes
- On Demo, we should be able to switch between default and striped Table

2024-02-27 14:31 UTC, astagnol commented on packages/components/src/table/documentation/usage-guidelines/usage.mdx
> +### Width
Width -> Variant

2024-02-28 16:38 UTC, aesteves60 approved these changes

2024-02-28 16:58 UTC, astagnol requested changes
Columns width acts a bit differently from native table. We can discuss about this

2024-03-01 13:56 UTC, astagnol approved these changes

2024-03-04 07:54 UTC, dpellier approved these changes

2024-03-04 07:54 UTC, merged