feat(timepicker): add new component
ovh/design-system pull request #388
Opened 2024-02-23 13:08 UTC by skhamvon

Add timepicker component

2024-02-26 08:10 UTC, dpellier requested changes
Issue on default demo on storybook when:
- changing current timezone => empty select
- toggling error => nothing happens

<img width="631" alt="Capture d’écran 2024-02-26 à 09 08 22" src="https://github.com/ovh/design-system/assets/1390934/9e47e109-aab7-4b84-abd0-53674b7c14dd">

2024-02-28 08:27 UTC, astagnol requested changes
When you change something in the controls (for example disabled from false to true), the field is cleared. (this is not happening on Input component of type time)

2024-03-04 08:00 UTC, dpellier requested changes
Same issue a basic input about clearable button still focusable when disabled
(https://github.com/ovh/design-system/pull/293#pullrequestreview-1913581661)
waiting for resolution on v18 branch, then rebase and retest here

2024-03-06 09:08 UTC, Leotheluck approved these changes

2024-03-14 14:53 UTC, merged