Fix/input focus on clear
ovh/design-system pull request #390
Opened 2024-02-28 16:14 UTC by aesteves60

Focus on input when clear
Add focusable icon according to this PR https://github.com/ovh/design-system/pull/382 This PR was merge in V18

2024-02-29 08:11 UTC, dpellier requested changes
Back tabbing does not work properly.
- go to the demo
- set clearable true
- focus input
  - tab -> button focused => ok
  - shift+tab -> focus is not on the input => ko, input should be focused again

(also does not work on Safari)

2024-02-29 10:00 UTC, astagnol requested changes
shift + tab doesn't work properly

But in Safari v17.3.1:
- set clearable true
- focus input
- tab -> button focused => ok for me but no style is applied while focused

But there was the same issue here and it has been fixed (and merged in refactor/input-attrs): https://github.com/ovh/design-system/pull/382 (check my resolved comment)

2024-03-06 08:19 UTC, dpellier approved these changes
fix e2e then it looks good

2024-03-06 09:25 UTC, Leotheluck approved these changes

2024-03-08 14:52 UTC, astagnol approved these changes

2024-03-11 08:38 UTC, merged