refactor(skeleton): migrate arch v18
ovh/design-system pull request #405
Opened 2024-03-19 15:08 UTC by aesteves60

First step in skeleton v18 migration

2024-03-20 08:14 UTC, dpellier requested changes

2024-03-20 08:14 UTC, dpellier commented on packages/storybook/stories/components/skeleton/1_specifications.stories.mdx
> +Skeleton TODO add small description:
Replace

2024-03-20 08:14 UTC, dpellier commented on packages/ods/src/components/skeleton/documentation/migration.from.17.x.mdx
> +## Attributes changes
This doc is a really important part of the transition adoption to v18, treat each attribute separately and add a dedicated example for each

2024-03-20 08:14 UTC, dpellier commented on packages/ods/src/components/skeleton/documentation/migration.from.17.x.mdx
> +`ramdomized` <img src="https://img.shields.io/badge/removed-FF0000" />
typo: `randomized`

2024-03-20 08:14 UTC, dpellier commented on packages/storybook/stories/components/skeleton/4_demo.stories.ts
> +    customCss: {
good idea 👍, we'll update the previous compo with the same control

2024-03-20 09:07 UTC, astagnol approved these changes

2024-03-20 13:33 UTC, dpellier requested changes
- style should be more simple
- need only one mixin to obtain skeleton rendering

2024-03-21 08:06 UTC, dpellier requested changes

2024-03-21 08:06 UTC, dpellier commented on packages/ods/src/style/_skeleton.scss
>    transform: translateY(-50%);
should be removed, used previously in conjonction with the `top` value

2024-03-21 08:06 UTC, dpellier commented on packages/ods/src/style/_skeleton.scss
> +  width: 100%;
not needed with `display: block` that the default value

2024-03-21 09:10 UTC, dpellier approved these changes

2024-03-21 14:56 UTC, merged