feat(tag): implement component
ovh/design-system pull request #419
Opened 2024-04-11 07:32 UTC by dpellier

2024-04-11 12:15 UTC, aesteves60 requested changes

2024-04-11 12:15 UTC, aesteves60 commented on packages/ods/src/style/_tag.scss
> +@mixin ods-tag() {
I think it miss the font family

2024-04-11 12:17 UTC, aesteves60 requested changes

2024-04-11 12:17 UTC, aesteves60 commented on packages/storybook/stories/components/tag/tag.stories.ts
> +        type: { summary: ODS_ICON_NAMES }
For the icon the list is very long, maybe a link to the icon doc should be better

2024-04-11 15:07 UTC, astagnol approved these changes

2024-04-12 07:03 UTC, astagnol requested changes
- Close Icon in Tag md size should be 1rem instead of 0.875 and the one in lg size should be 1.25rem instead of 1rem.

- Tag in small spaces:
<img width="662" alt="Capture d’écran 2024-04-12 à 08 57 52" src="https://github.com/ovh/design-system/assets/53512103/327248b9-a3c5-43b2-b882-afe707d9bcfb">

2024-04-12 08:30 UTC, aesteves60 approved these changes

2024-04-12 08:31 UTC, merged