Refactor/ods input
ovh/design-system pull request #429
Opened 2024-04-15 14:56 UTC by aesteves60

2024-04-17 08:25 UTC, dpellier requested changes

2024-04-17 08:25 UTC, dpellier commented on packages/ods/src/components/input/tests/navigation/ods-input.e2e2.ts
> +import type { E2EElement, E2EPage } from '@stencil/core/testing';
file name is wrong `e2e2` => `e2e`

2024-04-17 08:25 UTC, dpellier commented on packages/ods/src/components/input/tests/navigation/ods-input.e2e2.ts
> +      await button.click();
miss en expect between Enter and click

2024-04-17 08:25 UTC, dpellier commented on packages/ods/src/components/input/tests/navigation/ods-input.e2e2.ts
> +      await page.keyboard.press(' ');
either use ` ` or `Space` to be consistent with other tests

2024-04-17 08:25 UTC, dpellier commented on packages/ods/src/components/input/tests/navigation/ods-input.e2e2.ts
> +      await button.click();
same expect here

2024-04-17 08:25 UTC, dpellier commented on packages/ods/src/components/input/package.json
> +    "lint:ts": "eslint 'src/**/*.{js,ts,tsx}'",
update with latest cmd (check other components)

2024-04-17 08:25 UTC, dpellier commented on packages/ods/src/components/input/tests/rendering/ods-input.e2e.ts
> +  describe('method:clear', () => {
not sure this is the right place for those
`rendering` should contains the tests about things that change the actual render (ex: setting is-loading does display a spinner, is-masked add a button, ...)
we can add specific directories like `methods` and `events` that will contains dedicated tests

2024-04-17 08:25 UTC, dpellier commented on packages/ods/src/components/input/tests/rendering/ods-input.spec.ts
> +      it('should not be set by default', async() => {
rename

2024-04-17 08:25 UTC, dpellier commented on packages/ods/src/style/_input.scss
> +  font-size: 16px;
`1rem`

2024-04-17 08:25 UTC, dpellier commented on packages/ods/src/style/_input.scss
> +  line-height: 16px;
`1rem`

2024-04-17 08:25 UTC, dpellier commented on packages/ods/vue/tests/_app/src/components/ods-input.vue
> +  <ods-input name="ods-input" @ods-value-change="() => console.log('test')"></ods-input>
use `onOdsValueChange`?

2024-04-17 08:25 UTC, dpellier commented on packages/ods/vue/tests/e2e/ods-input.e2e.ts
> +});
test value change?

2024-04-17 08:25 UTC, dpellier commented on packages/storybook/stories/components/input/migration_.from.17.x.mdx
> +<Meta of={SkeletonStories} name='Migration From 17.x' />
`InputStories`

2024-04-17 08:25 UTC, dpellier commented on packages/storybook/stories/components/input/migration_.from.17.x.mdx
> +# Skeleton - migrate from v17 to v18
`Input`

2024-04-17 08:25 UTC, dpellier commented on packages/storybook/stories/components/input/migration_.from.17.x.mdx
> +You can replace it a regax on the `pattern` attributes.
"You can replace it with a regex on the `pattern` attribute."

2024-04-17 08:25 UTC, dpellier commented on packages/storybook/stories/components/input/migration_.from.17.x.mdx
> +For add a label on the input wrapped it with the component `form-field`.
`To add a label ...`

2024-04-17 08:25 UTC, dpellier commented on packages/storybook/stories/components/input/migration_.from.17.x.mdx
> +No need anymore. Can't be migrate.
`This feature is not supported anymore`

2024-04-17 09:27 UTC, aesteves60 commented on packages/ods/src/components/input/src/components/ods-input/ods-input.tsx
> +  @Prop({ mutable: true, reflect: true }) public value?: string | number = undefined;
Don't think the value should be need

2024-04-17 09:28 UTC, aesteves60 commented on packages/ods/src/components/input/src/components/ods-input/ods-input.tsx
> +    return;
It's for return void and not a `Promise<CustomEvent<void>>` if I return `this.odsClear.emit()`

2024-04-17 09:29 UTC, dpellier commented on packages/ods/src/components/input/src/components/ods-input/ods-input.tsx
> +  @Prop({ mutable: true, reflect: true }) public value?: string | number = undefined;
my bad I saw an initialization but of wrong type so `?` fixes it

2024-04-17 09:31 UTC, dpellier commented on packages/ods/src/components/input/src/components/ods-input/ods-input.tsx
> +    return;
just don't return anything?
```
async clear(): Promise<void> {
    if (this.isDisabled) {
      return;
    }
    this.value = undefined;
    this.odsClear.emit();
  }
```

2024-04-17 13:43 UTC, aesteves60 commented on packages/ods/src/components/input/src/components/ods-input/ods-input.tsx
> +  @Prop({ reflect: true }) public isClearable?: boolean;
ok but not masked

2024-04-17 13:46 UTC, aesteves60 commented on packages/ods/src/components/input/src/components/ods-input/ods-input.tsx
> +  @Event() odsValueChange!: EventEmitter<OdsInputEventValueChange>;
If you want, but I don't think it will fix the problem caused by the integrator's misunderstanding.

2024-04-18 07:16 UTC, dpellier requested changes

2024-04-18 07:16 UTC, dpellier commented on packages/ods/src/components/input/src/components/ods-input/ods-input.tsx
> +  @Prop({ reflect: true }) public isRequired?: boolean = false;
you can remove the `?` then if the prop has a default value

2024-04-18 07:16 UTC, dpellier commented on packages/ods/src/components/input/tests/behaviour/ods-input.e2e.ts
> +describe('ods-input accessibility', () => {
rename

2024-04-18 07:16 UTC, dpellier commented on packages/ods/src/components/input/tests/rendering/ods-input.spec.ts
> +      it('should not be set by default with type "text"', async() => {
should be set by default with ...

2024-04-18 07:21 UTC, dpellier requested changes
I see already a few issue with the actions:
- clearable should appear only after more than 1 character si typed
- clearable color should be gray
- focus is square on the actions (clearable, masked), did you use the mixin?
- cursor on actions should be the same as an ods-button
- actions icon is not correctly centered vertically

2024-04-18 08:40 UTC, astagnol requested changes
Eye icon should not be displayed by default when we arrive on Demo page
![Capture d’écran 2024-04-18 à 09 11 42](https://github.com/ovh/design-system/assets/53512103/dd569165-6622-4e3e-820a-2be318a39c08)

Types in the field on Demo -> should not be in error state.

On Demo, set 'isMasked' to false and 'type' to number:
![Capture d’écran 2024-04-18 à 09 14 23](https://github.com/ovh/design-system/assets/53512103/5b8ca10b-f52a-4979-a59e-8b41287306fc)

Click on the field -> move your mouse outside -> border color is now blue (it should not change)

**isClearable**
- When isClearable is true, icon should be displayed after user types one character.
- clearable icon is a secondary icon, it should be in neutral-600

We should have a cursor pointer when you hover clearable and eye icons.

When the user types in the field, text color should be ods-color-text.

**Disabled**
Style should not change on hover.

**Accessibility**
- focus on icon is not correct (UI). It should be same as:
![Capture d’écran 2024-04-18 à 09 58 23](https://github.com/ovh/design-system/assets/53512103/d1ff9ff7-3a1e-4a0a-8fa9-16c8d394bee6)
- cannot focus on isClearable icon when eye icon is displayed

2024-04-19 09:04 UTC, dpellier requested changes

2024-04-19 09:04 UTC, dpellier commented on packages/ods/src/components/input/src/index.ts
> +export { type OdsInputEventValueChange } from './interfaces/events';
expose detail also

2024-04-19 09:09 UTC, dpellier requested changes

2024-04-19 09:09 UTC, dpellier commented on packages/ods/src/components/input/src/components/ods-input/ods-input.tsx
> +  @Event() odsBlur!: EventEmitter<void>;
We should also trigger an `odsFocus` event

2024-04-19 09:34 UTC, dpellier requested changes

2024-04-19 09:34 UTC, dpellier commented on packages/ods/src/components/input/src/controller/ods-input.ts
> +  internals?.setFormValue?.(value?.toString() ?? '');
remove unnecessary `?`
`internals.setFormValue(value?.toString() ?? '');`

2024-04-19 09:54 UTC, dpellier requested changes
Got this warning when trying to reset an input without default value set
<img width="721" alt="Capture d’écran 2024-04-19 à 11 54 14" src="https://github.com/ovh/design-system/assets/1390934/34fa88b7-78cd-4a67-99e3-8e7652552b1f">

2024-04-19 12:47 UTC, astagnol requested changes
Types in the field on Demo -> should not be in error (it is working well on documentation page)

**isClearable**
Focus should be back to the field when it has been cleared (on both mouse click & keyboard nav)

**Disabled & readonly**
I updated the figma so you can now use the following variables (you'll need to re-generate the tokens):
$ods-form-element-foreground-color-disabled
$ods-form-element-foreground-color-readonly

**Accessibility**
Focus on icon is still not correct (but the icon is not aligned vertically by the way, same goes for loading icon)
<img width="531" alt="Capture d’écran 2024-04-19 à 14 26 56" src="https://github.com/ovh/design-system/assets/53512103/8efb774e-387f-4606-8ebf-17f022b47733">

Why display false or true at the top the field for this control?
<img width="524" alt="Capture d’écran 2024-04-19 à 14 45 44" src="https://github.com/ovh/design-system/assets/53512103/46e2e073-be7e-4ab8-8656-8e7214dc384f">

2024-04-19 12:57 UTC, dpellier commented on packages/ods/src/components/input/src/components/ods-input/ods-input.scss
> +    &--disabled {
can be moved into the mixin using native pseudo-selector `&:disabled` and then remove the class from the template
(when possible it's better to use native pseudo, this way people get it when using the mixin without depending on BEM class name)

2024-04-19 12:57 UTC, dpellier commented on packages/ods/src/components/input/src/components/ods-input/ods-input.scss
> +      user-select: none;
not sure needed

2024-04-22 07:47 UTC, dpellier requested changes

2024-04-22 07:47 UTC, dpellier commented on packages/ods/src/components/input/src/components/ods-input/ods-input.tsx
> +  @Watch('error')
should be removed, there is no more any prop `error`

2024-04-22 07:47 UTC, dpellier commented on packages/ods/src/components/input/src/components/ods-input/ods-input.tsx
> +    this.internalError = !this.inputEl?.validity?.valid ?? this.hasError;
is `internalError` state still usefull?

2024-04-22 09:57 UTC, dpellier requested changes

2024-04-22 09:57 UTC, dpellier commented on packages/ods/src/components/input/tests/rendering/ods-input.spec.ts
> +  describe('methods', () => {
move to behaviour spec file too

2024-04-22 13:31 UTC, dpellier requested changes
please check remaining unresolved previous reviews

2024-04-22 13:31 UTC, dpellier commented on packages/ods/src/components/input/tests/behaviour/ods-input.spec.ts
> +describe('ods-input rendering', () => {
rename

2024-04-23 12:32 UTC, dpellier requested changes
readonly state still has active action buttons

2024-04-23 12:32 UTC, dpellier commented on packages/ods/src/components/input/src/components/ods-input/ods-input.scss
> +      font-size: 16px;
1rem

2024-04-23 12:32 UTC, dpellier commented on packages/ods/src/components/input/src/components/ods-input/ods-input.scss
> +        pointer-events: none;
would be best to manage this on the button style instead
update the `:active` selector with a `:not(:disabled)`

2024-04-23 13:17 UTC, feoche requested changes
Global : 
- [ ] Not working in Safari 16.1 (this.attachInternals is not a function)

Docs : 
- [x] Missing links below Component overview
- [x] Missing readonly + placeholder examples
- [x] Using "My button" text in Migration doc instead of input

Demo : 
- [ ] A11y issues (to be discussed) : 
![image](https://github.com/ovh/design-system/assets/5332505/9cf803b1-0b77-48b3-a068-1af4c6701449)

Style : 
- [ ] Text is overflowed on loading state
![image](https://github.com/ovh/design-system/assets/5332505/b684627e-a330-4d2b-b5ab-0ddff6d8d5b2)
- [ ] Icon inside action button is not vertically aligned, fixed by setting a font-size on the button itself
![image](https://github.com/ovh/design-system/assets/5332505/b4cbb968-48af-4b6a-940d-69270bdfb8e2)
- [x] Spinner should be 8px away from right border (in loading state) instead of 4px
- [ ] Icons in action buttons are not centered in Chromium
![image](https://github.com/ovh/design-system/assets/5332505/b28800aa-3ab7-4af0-b6bf-1fcb5a6f325b)
- [x] Loading icon has a cursor: pointer on it
- [ ] Input of type `number` show arrow icons in Chromium when hover/focus
- [ ] Is `pattern` attribute working ?

2024-04-23 15:12 UTC, aesteves60 commented
>     * [ ]  Is `pattern` attribute working ?

Yes but we don't update the error anymore. The error is return in the `odsChange` event

2024-04-24 07:56 UTC, dpellier requested changes
issue with input type `number` and `isClearable` true:
- type a number, like `11`
=> clearable is visible
- type a letter `11e`
=> clearable disappear

I guess the value is reset when not matching a number, but input should stay clearable in that case

2024-04-24 08:51 UTC, feoche requested changes
- [ ] Not vertically aligned in Chromium, can be fixed using `display: inherit` + `justify-content: center` + `align-items: center`
![image](https://github.com/ovh/design-system/assets/5332505/c3f19d76-3eba-40be-9f35-7eb9a94546c0)

2024-04-24 14:50 UTC, dpellier approved these changes

2024-04-25 08:17 UTC, Leotheluck approved these changes

2024-04-25 08:17 UTC, feoche approved these changes

2024-04-25 12:00 UTC, merged