feat(storybook): add component DocNavigator
ovh/design-system pull request #431
Opened 2024-04-16 09:09 UTC by astagnol

DocNavigator displays in Documentation a button to the Demo page and a link to the Zeroheight specifications

2024-04-16 09:29 UTC, dpellier requested changes

2024-04-16 09:29 UTC, dpellier commented on packages/storybook/package.json
> +    "@storybook/addon-links": "^8.0.8",
never use "^" and set the same version as other
`"@storybook/addon-links": "8.0.4",`

2024-04-16 09:29 UTC, dpellier commented on packages/storybook/stories/doc-navigator.tsx
> +              const baseUrl = 'https://zeroheight.com/6fc8a63f7/p/';
could be moved to the same place as the link ids enum

2024-04-16 09:31 UTC, dpellier commented on packages/storybook/stories/doc-navigator.tsx
> +          label={'Go to Zeroheight'}
Maybe a less tool-oriented label? (Go to functional specification?)
BTW for fixed string you can omit the `{}` (`label="label"`)

2024-04-16 13:01 UTC, aesteves60 commented on packages/storybook/stories/doc-navigator.tsx
> +            variant={'default'}
Use the enum

2024-04-16 13:02 UTC, aesteves60 commented on packages/storybook/stories/doc-navigator.tsx
> +          icon={'external-link'}
use the enum ODS_ICON_NAME

2024-04-16 13:04 UTC, aesteves60 commented on packages/storybook/stories/zeroheight-link-ids.ts
> +export enum ZeroheightLinkIds {
export should be at the end of the file

2024-04-17 07:14 UTC, dpellier approved these changes

2024-04-17 07:43 UTC, aesteves60 approved these changes

2024-04-17 08:54 UTC, merged