feat(table): implement component
ovh/design-system pull request #432
Opened 2024-04-16 13:34 UTC by dpellier

2024-04-16 14:48 UTC, aesteves60 requested changes

2024-04-16 14:48 UTC, aesteves60 commented on packages/storybook/stories/components/table/documentation.mdx
> +You can apply your own style on each part of the table directly.
No part

2024-04-16 14:48 UTC, aesteves60 commented on packages/ods/src/components/table/src/components/ods-table/ods-table.scss
> +  $table: &;
unused

2024-04-16 15:11 UTC, astagnol requested changes
Cannot start React app in examples

2024-04-17 07:42 UTC, astagnol approved these changes

2024-04-17 12:22 UTC, merged