feat(textarea): implement component
ovh/design-system pull request #438
Opened 2024-04-25 12:37 UTC by dpellier

2024-04-26 08:35 UTC, feoche requested changes
Docs :
- [ ] API : `spellcheck` attribute does not have the `is/has` prefix ?
- [ ] Examples : missing "Readonly" & "Spellcheck"
- [ ] Migration guide : missing "Forbidden values", "Inline" & "Size"

2024-04-26 08:54 UTC, dpellier commented
`Migration guide : missing "Forbidden values", "Inline" & "Size"`
There is no `Forbidden values` prop on actual textarea.
Inline and Size are already there
<img width="886" alt="Capture d’écran 2024-04-26 à 10 52 59" src="https://github.com/ovh/design-system/assets/1390934/a65dea8f-8ec1-4356-857b-17ff89ad9229">

2024-04-26 08:57 UTC, feoche commented
"Inline and Size are already there" : yes, but they miss their migration examples below, sorry for the lack of precision

2024-04-26 14:55 UTC, aesteves60 approved these changes

2024-04-29 08:18 UTC, feoche approved these changes

2024-04-29 08:19 UTC, Leotheluck approved these changes

2024-04-29 08:23 UTC, merged