feat(breadcrumb): implement component
ovh/design-system pull request #440
Opened 2024-04-29 08:26 UTC by dpellier

- update ods-link to allow icon-only link (waiting for design input on this as the rendering on breadcrumb is strange)
- update doc generator to hide non public Prop (and update some component accordingly)
- KNOWN ISSUE: unable to prevent breadcrumb link on documentation page to not redirect on click

2024-04-29 12:43 UTC, feoche requested changes
### Documentation
- [x] Missing differentiating between Breadcrumb and BreadcrumbItem props
- [x] Missing differentiating between Breadcrumb and BreadcrumbItem events

### Style
- [ ] Pipe character "|" should have : `font-size: 1.1rem; line-height: 1.5rem; font-weight: 700`
- [ ] Add `aria-current="page"` attribute to last BreadcrumbItem (see https://a11y-style-guide.com/style-guide/section-navigation.html#kssref-navigation-breadcrumbs)

2024-04-30 14:52 UTC, feoche requested changes
- [x] Vertical alignment issue, font-sizes are fine (see example, top is staging, bottom is expected)
![image](https://github.com/ovh/design-system/assets/5332505/aad6df0c-6be8-4202-80f4-6da6a89f353d)

2024-05-02 08:01 UTC, aesteves60 requested changes

2024-05-02 08:08 UTC, feoche requested changes

2024-05-02 08:08 UTC, feoche commented on packages/ods/src/components/breadcrumb/src/components/ods-breadcrumb/ods-breadcrumb.scss
> +  align-items: center;
```suggestion
  align-items: baseline;
  line-height: 1rem;
```
does fix the global alignment with icons:
Before : 
![image](https://github.com/ovh/design-system/assets/5332505/36aef77e-f956-418e-aac0-bf09580bb553)

After :
![image](https://github.com/ovh/design-system/assets/5332505/9f8fd0c2-2989-49b1-8f2a-466ddf243a6b)

2024-05-02 09:15 UTC, aesteves60 approved these changes

2024-05-02 09:18 UTC, dpellier commented on packages/ods/src/components/breadcrumb/src/components/ods-breadcrumb-item/ods-breadcrumb-item.tsx
> +  @Event() odsBreadcrumbItemClick!: EventEmitter<globalThis.Event>;
Event is already imported as Stencil decorator, updated all to `MouseEvent` anyway

2024-05-02 09:21 UTC, feoche approved these changes

2024-05-02 09:27 UTC, Leotheluck approved these changes

2024-05-02 09:28 UTC, merged