feat(code): implement component
ovh/design-system pull request #446
Opened 2024-05-10 08:37 UTC by dpellier

As there are no specific designs for this component, I went with the simpliest version, which is the same as the actual.
Which means no toolip on copy button (unlike clipboard), could be added on another iteration if actually asked for.

2024-05-10 12:26 UTC, aesteves60 approved these changes

2024-05-13 12:26 UTC, Leotheluck approved these changes

2024-05-13 12:26 UTC, Leotheluck commented on packages/storybook/stories/components/code/documentation.mdx
> +## With copy button enabled
To match with the other documentations I would maybe only put "CanCopy", or "Can Copy"

2024-05-14 13:52 UTC, feoche requested changes
### Style
- [x] Padding should be 12px

2024-05-14 14:11 UTC, feoche approved these changes

2024-05-14 14:23 UTC, merged