refactor(password): implementation component
ovh/design-system pull request #447
Opened 2024-05-10 12:48 UTC by aesteves60

2024-05-10 13:22 UTC, dpellier requested changes

2024-05-10 13:22 UTC, dpellier commented on packages/ods/src/components/password/src/components/ods-password/ods-password.tsx
> +          onOdsChange={ this.onOdsChange.bind(this) }
would be nice to keep the same syntax everywhere, now we usually have:
```
={ () => this.method() }
```

2024-05-13 12:55 UTC, Leotheluck requested changes
## General
- [ ] The Eye icon should be grey if the component is disabled. (I would assume this is also the case for the loading spinner, but this specific case is not documented on the Figma.)

## Documentation
- [ ] Instead of `You can add your own style on the password element using the part input.`, we should prefer using `You can add your own style on the password component using '::part(input)'`
- [ ] Instead of `Allow just numeric character`, we should prefer using `With this pattern setting, the component will only allow for numeric characters:`

## Migration guide
- [ ] Instead of `To add a label on the input wrapped it with the component form-field.`, we should prefer using `To add a label on a password component, wrap it within a form-field component.`
- [ ] Instead of `Form components does not provide color variant anymore. You can use custom css if you need to customize the component.`, we should prefer using `Form components do not provide color variants anymore. You can use custom CSS if you need to customise the component.`
- [ ] We should add an example of a migration from `forbidden-values` to `pattern`.

2024-05-13 15:01 UTC, aesteves60 commented
* [ ]  Instead of `You can add your own style on the password element using the part input.`, we should prefer using `You can add your own style on the password component using '::part(input)'`
I let the previous version for stay the consistence with the others  component

2024-05-14 07:18 UTC, dpellier reviewed
does the mask button needs to be disabled on readonly?
purpose of the state is to let the input content still be readable

2024-05-14 08:21 UTC, Leotheluck requested changes
## Migration guide
- [ ] Form components does not provide color variant anymore. -> Form components do__ not provide color variant_s_ anymore. `(3 times)`
- [ ] Line break needed in `color` after `Has been removed`.

2024-05-14 09:28 UTC, Leotheluck approved these changes

2024-05-14 14:27 UTC, dpellier approved these changes

2024-05-14 14:30 UTC, feoche approved these changes

2024-05-14 14:40 UTC, feoche approved these changes

2024-05-14 14:41 UTC, merged