feat(quantiy): change padding to allow 4 digit
ovh/design-system pull request #45
Opened 2023-05-22 13:06 UTC by EnzoStll

2023-05-22 13:09 UTC, skhamvon commented on packages/stencil/components/quantity/src/index.html
> +  <osds-input style="max-width: 45px; padding: 0%" type="number" color="primary" min="1" max="9999" step="1
Peux tu enlever le padding inline ?
Pareil pour la ligne 31

2023-05-22 14:05 UTC, ovh-cds commented
CDS Report build-storybook#539.0 ✘  
* 
  * build ✘

2023-05-22 14:13 UTC, ovh-cds commented
CDS Report build-storybook#540.0 ✘  
* 
  * build ✘

2023-05-23 09:37 UTC, ovh-cds commented
CDS Report build-storybook#540.1 ✘  
* 
  * build ✘

2023-05-23 11:55 UTC, ovh-cds commented
CDS Report build-storybook#540.2 ✘  
* 
  * build ✘

2023-05-23 13:13 UTC, astagnol requested changes
Nice! But you should update the following things:
- in osds-quantity.e2e.screenshot.ts: add style="width: 45px" to <osds-input> and <input> so screenshot tests will be similar to expected integration (up to 4 digits input)
- in index.html: modify max-width to width since integrator should set the width of the specific input and not define the maximum size the input element is allow to have
- for e2e tests, I'll call you :)

2023-06-27 12:34 UTC, closed without merging