feat(form-field): implement component
ovh/design-system pull request #450
Opened 2024-05-14 15:43 UTC by Leotheluck

## A Form Field component is used to wrap several form components with logic, visual hints and additional styling.

Known issue:
- The link towards `technical specifications` is currently broken, will be fixed later in another pull request.

2024-05-15 07:13 UTC, dpellier requested changes

2024-05-15 07:13 UTC, dpellier commented on packages/ods/src/components/form-field/src/components/ods-form-field/ods-form-field.scss
> +  position: relative;
should be useless

2024-05-15 07:13 UTC, dpellier commented on packages/ods/src/components/form-field/src/components/ods-form-field/ods-form-field.scss
> +    width: 100%;
should be useless

2024-05-15 07:13 UTC, dpellier commented on packages/ods/src/components/form-field/src/components/ods-form-field/ods-form-field.scss
> +    flex-direction: row;
add a `column-gap` to ensure spacing if label is long enough to reach the second element

2024-05-15 07:13 UTC, dpellier commented on packages/ods/src/components/form-field/src/components/ods-form-field/ods-form-field.scss
> +    margin-bottom: 4px;
remove, use a `row-gap` on parent instead

2024-05-15 07:13 UTC, dpellier commented on packages/ods/src/components/form-field/src/components/ods-form-field/ods-form-field.scss
> +    margin-top: 4px;
remove, use a `row-gap` on parent instead

2024-05-15 07:13 UTC, dpellier commented on packages/ods/src/components/form-field/tests/rendering/ods-form-field.e2e.ts
> +    expect(labelSlot.textContent).toEqual('Label');
`toBe`

2024-05-15 07:13 UTC, dpellier commented on packages/ods/src/components/form-field/tests/rendering/ods-form-field.e2e.ts
> +    expect(visualHintSlot.textContent).toEqual('Visual Hint');
`toBe`

2024-05-15 07:13 UTC, dpellier commented on packages/ods/src/components/form-field/tests/rendering/ods-form-field.e2e.ts
> +    expect(helperSlot.textContent).toEqual('Helper');
`toBe`

2024-05-15 07:13 UTC, dpellier commented on packages/ods/src/components/form-field/tests/rendering/ods-form-field.e2e.ts
> +    expect(errorMessage?.textContent).toEqual('Wrong format.');
`toBe`

2024-05-15 07:13 UTC, dpellier commented on packages/storybook/stories/components/form-field/documentation.mdx
> +You can add your own style on the form-field elements using `::part` or by directly updating the slot elements.
feels weired to mention parts here as they can use whatever they want in the form-field, not always ods with parts

2024-05-15 07:13 UTC, dpellier commented on packages/storybook/stories/components/form-field/form-field.stories.ts
> +export const Default: StoryObj = {
Default would be the bare minimum required, in this case only input
Maybe use one of the complete one for the top doc page overview to have a better exemple and update this one?

2024-05-15 10:04 UTC, feoche requested changes
### Documentation
- [x] Style customization : prefer something less flashy (i.e. #b63f81 as text color)
- [x] Style customization : remove visual hint slot
- [x] Examples : put slotted examples above "Error" one
- [x] Examples : Tooltip → Use `help-circle` icon instead of "(???)"

### Demo
- [x] Change `mainSlot` control into `content`, no description (only `string` appears)
- [x] Default content
  - [x] Label should be 14px semibold / #4d5592
  - [x] Visual hint should be 12px regular / #4d5592
  - [x] Helper message should be 12px regular / #4d5592
  - [x] Error message should be 12px semi-bold #bf0020

### Style
- [x] Visual hint slot should be in bottom right part (see example below)
![image](https://github.com/ovh/design-system/assets/5332505/cd3ab10c-1317-499b-8bdc-3d7cd7f046ef)

2024-05-15 15:31 UTC, dpellier requested changes
Style customization does not work
<img width="900" alt="Capture d’écran 2024-05-15 à 17 30 34" src="https://github.com/ovh/design-system/assets/1390934/39ce1eff-87f1-4f4e-90c2-9168526cffa8">

2024-05-15 15:32 UTC, dpellier requested changes
Change textarea example to a number of character typed value instead, like `11/200`
<img width="881" alt="Capture d’écran 2024-05-15 à 17 31 38" src="https://github.com/ovh/design-system/assets/1390934/f14deb18-1495-4e29-a1e3-0d3a189897b3">

2024-05-17 08:26 UTC, feoche requested changes
### General
- [ ] Set input and textarea with "Placeholder" `placeholder` only, no value
- [x] Set visual hint text to `0/100`

### Documentation
- [x] Put Tooltip icon inside "label" slot, at the end

### Demo
- [x] Change `caption` visual hint into `span` preset

2024-05-20 09:30 UTC, feoche commented
[ ] Fix conflicts

2024-05-22 07:33 UTC, dpellier approved these changes

2024-05-22 08:17 UTC, feoche approved these changes

2024-05-22 09:50 UTC, astagnol approved these changes

2024-05-23 08:17 UTC, merged