refactor(radio): implementation component
ovh/design-system pull request #456
Opened 2024-05-22 15:33 UTC by aesteves60

2024-05-23 08:07 UTC, aesteves60 commented on packages/ods/src/components/radio/src/components/ods-radio/ods-radio.tsx
> +  @Event() odsFocus!: EventEmitter<void>;
I think it's useless to have a reset methods / event because there are not default value

2024-05-23 08:59 UTC, feoche requested changes
## Documentation
- [ ] Overview : prefer checked version
- [ ] Missing single "checked" example
- [ ] InputId : Add an explanation about its usage

## Demo
- [ ] Demo Group : Add an explanation text about what isChecked* and isDisabled* do

## Style
- [x] Remove focus outline when checking Radio (prefer `focus-visible`)

2024-05-23 09:12 UTC, astagnol requested changes
When you click on the radio, outline should not be displayed (on Firefox & Chromium, Safari is fine)

2024-05-23 09:12 UTC, astagnol commented on packages/ods/src/components/radio/src/index.html
> +    <ods-radio input-id="multiligne" name="multiligne" value="multiligne"></ods-radio>
typo: multiligne -> multiline

2024-05-23 09:12 UTC, astagnol commented on packages/storybook/stories/components/radio/migration.from.17.x.mdx
> +You have now an event for know want the component is focus.
typo: "to know when the component is focused?"

2024-05-23 13:11 UTC, aesteves60 commented on packages/ods/src/components/radio/src/components/ods-radio/ods-radio.tsx
> +  @Event() odsFocus!: EventEmitter<void>;
Reset now remove the current checked radio and checked the radio in the group with the `is-checked` attribute

2024-05-23 14:53 UTC, astagnol approved these changes

2024-05-29 07:43 UTC, dpellier requested changes

2024-05-29 07:43 UTC, dpellier commented on packages/storybook/stories/components/radio/documentation.mdx
> +The radio is not default vertical align because you can make everythink after (text, image, icon...).
```
The radio component may not be vertically aligned by default, depending on the content following it.
You'll need to manage this with css on parent element.
```

2024-05-29 13:50 UTC, dpellier approved these changes

2024-05-29 15:09 UTC, Leotheluck approved these changes

2024-05-31 08:57 UTC, merged