fix(tooltip): fix examples & demo alignment
ovh/design-system pull request #458
Opened 2024-05-23 15:44 UTC by astagnol

Tooltip example is now centred correctly

2024-05-24 13:49 UTC, feoche requested changes
## Documentation
- [ ] Style customization : Set tooltip position the same as in "Default" example

## Demo
- [x] Set "top" as default position

2024-05-27 08:05 UTC, feoche approved these changes

2024-05-27 08:07 UTC, dpellier approved these changes

2024-05-28 07:39 UTC, aesteves60 approved these changes

2024-05-28 07:50 UTC, Leotheluck approved these changes

2024-05-28 08:00 UTC, merged