refactor(checkbox): implementation component
ovh/design-system pull request #460
Opened 2024-05-30 14:24 UTC by aesteves60

2024-05-31 07:25 UTC, dpellier requested changes

2024-05-31 07:25 UTC, dpellier commented on packages/ods/src/components/checkbox/src/index.ts
> +export { OdsCheckbox } from './components/ods-checkbox/ods-checkbox';
export events

2024-05-31 07:25 UTC, dpellier commented on packages/ods/src/style/_checkbox.scss
> +    transform: scale(0);
why are you using a scale transormation on icon?

2024-05-31 07:25 UTC, dpellier commented on packages/storybook/stories/components/checkbox/documentation.mdx
> +The previous components `checkbox` and `checkbox-button` have now been included in `checkbox`
should be in the migration page under `Usage changes`

2024-05-31 07:25 UTC, dpellier commented on packages/ods/src/components/checkbox/src/components/ods-checkbox/ods-checkbox.tsx
> +  @Prop({ reflect: true }) public inputId?: string;
should be before `isChecked` to follow alphabetical order

2024-05-31 09:55 UTC, astagnol requested changes
- Overview : prefer checked version (like radio)
- On Safari, need to "tab" twice to focus the component

2024-05-31 12:11 UTC, aesteves60 commented
On Safari, need to "tab" twice to focus the component

Don't have browser stack licence I can't test it

2024-05-31 12:12 UTC, dpellier requested changes

2024-05-31 12:12 UTC, dpellier commented on packages/storybook/stories/components/checkbox/documentation.mdx
>  There is no longer a `checkbox` component to make clickable Element.
same, into `## Usages changes` was part of previous comment :)

2024-05-31 12:26 UTC, dpellier requested changes
Radio doc is no more visible on stroybook `Form` section

2024-05-31 12:33 UTC, dpellier approved these changes

2024-06-04 07:24 UTC, astagnol approved these changes

2024-06-04 08:57 UTC, feoche requested changes
## Documentation
- [ ] Put "Indeterminate" example after "Checked"
- [ ] Move "Alignment" example after "InputId"

2024-06-04 09:00 UTC, dpellier commented
@feoche I think it's best to stick as close as possible to an alphabetical order matching the prop names, as it is unopiniated.
Not everyone come on this page with the same context/expectation/vision, thus doesn't expect to find the same order.

2024-06-04 09:03 UTC, feoche approved these changes

2024-06-04 09:07 UTC, merged