refactor(switch): implement component
ovh/design-system pull request #464
Opened 2024-06-11 12:48 UTC by aesteves60

2024-06-11 14:39 UTC, feoche requested changes
## Documentation
- [x] Overview : Select first item by default

## Demo
- [x] Setting `isDisabled` resets the component

## Style
- [x] Focus' style should be the same as the hover style + its focus outline

2024-06-11 14:39 UTC, astagnol requested changes
- For global UAT, see François Eoche comment
- Fix e2e test

2024-06-11 15:07 UTC, dpellier requested changes

2024-06-18 12:09 UTC, aesteves60 commented on packages/ods/src/components/switch/src/components/ods-switch/ods-switch.tsx
> +  shadow: true,
With the radio, it's work with the form so I don't think it's relevent

2024-06-21 08:05 UTC, astagnol requested changes
- fix linters
- When an item is checked and the Switch is disabled, we should keep checked style with an opacity

2024-06-24 07:11 UTC, dpellier requested changes

2024-06-24 07:11 UTC, dpellier commented on packages/examples/react-webpack/package.json
> +    "formik": "^2.4.6",
no `^`

2024-06-24 12:16 UTC, dpellier requested changes
Still need to handle onKeyDown for Space to prevent scroll down on Firefox

2024-06-25 12:18 UTC, dpellier approved these changes

2024-06-25 12:26 UTC, feoche approved these changes

2024-06-25 12:27 UTC, astagnol approved these changes

2024-06-25 13:08 UTC, merged