feat(file-upload): implement component
ovh/design-system pull request #465
Opened 2024-06-11 12:52 UTC by dpellier

2024-06-11 14:59 UTC, feoche requested changes
## Style
- [ ] When having global error, a Divider should be displayed
- [ ] When having global error, border should be in red color

2024-06-12 07:18 UTC, Leotheluck reviewed
## General
- [ ] Should we remove the line "Accepted files:" if nothing is specified?

## Migration guide
- [ ] Should we remove the migration guide page as there is no migration possible?

2024-06-12 07:18 UTC, Leotheluck commented on packages/storybook/stories/components/file-upload/documentation.mdx
> +File-upload allow users to select one or more files to upload to a specific location:
allows*

2024-06-12 07:18 UTC, Leotheluck commented on packages/storybook/stories/components/file-upload/documentation.mdx
> +The component does not handle any actual upload, nor it knows the status of each file (regarding progress or error),
The component does not actually handle any upload, nor does it know the status of each file*

2024-06-12 07:18 UTC, Leotheluck commented on packages/storybook/stories/components/file-upload/documentation.mdx
> +This is an extend of the native `File` interface with optional attribute that you can set to alter the display:
extension*

2024-06-12 07:18 UTC, Leotheluck commented on packages/storybook/stories/components/file-upload/documentation.mdx
> +- `error`: set this if the upload of the file fail, to display an error message near it on the component file list.
set this if the upload of the file fails, in order to display an error message below the file list.*

2024-06-17 10:06 UTC, feoche requested changes
## Style
- [x] Global error should be left-aligned

## Demo
- [ ] Add in `accepted` description : "Bound to native file upload behavior. For label, use `acceptedFileLabel` attribute"

2024-06-18 09:57 UTC, feoche approved these changes

2024-06-18 14:36 UTC, astagnol approved these changes

2024-06-19 09:17 UTC, aesteves60 approved these changes

2024-06-20 07:48 UTC, feoche approved these changes

2024-06-20 07:56 UTC, merged