feat(accordion): implement component
ovh/design-system pull request #466
Opened 2024-06-12 14:37 UTC by Leotheluck

> An Accordion is a vertical header that reveals or hides an associated section of content.

2024-06-13 12:20 UTC, dpellier requested changes
Feels really weird to not be able to click on the summary text to toggle.
May be better to make the whole container clickable and use the same cursor (also when disabled) on the text and the surroudings.

Also the focus when opened looks really weird:
<img width="538" alt="Capture d’écran 2024-06-13 à 14 11 35" src="https://github.com/ovh/design-system/assets/1390934/7e72e477-812d-449d-9763-e79f8cd3bcb4">

2024-06-14 09:18 UTC, Leotheluck commented on packages/ods/src/components/accordion/src/components/ods-accordion/ods-accordion.scss
> +    margin-top: -1.25rem;
This is just to animate the accordion content so it slides from top to down, should I rather use transform translate?

2024-06-17 13:00 UTC, astagnol requested changes
<img width="1136" alt="Capture d’écran 2024-06-17 à 14 54 19" src="https://github.com/ovh/design-system/assets/53512103/b3941239-4c3e-462f-a90a-d9dc5ed75873">
We should not display the arrow marker of details tag (visible on Safari v17.3.1 )

2024-06-17 13:34 UTC, dpellier commented on packages/ods/src/components/accordion/src/components/ods-accordion/ods-accordion.tsx
> +          onKeyDown={(event) => this.handleKeyDown(event)}
You'll have to preventDefault onKeyDown for space, to prevent page scroll (Firefox), see select or tag

2024-06-17 13:35 UTC, dpellier commented on packages/ods/src/components/accordion/src/components/ods-accordion/ods-accordion.tsx
> +      <Host class='ods-accordion'>
use `"` when direct attribute, (`'` are used in JSX interpretation, like dynamic class)

2024-06-21 08:41 UTC, astagnol requested changes
- rebase with refactor/ods with new icons
- need to rework some paddings between summary and the wrapper__content, check Figma

2024-06-27 08:07 UTC, dpellier approved these changes

2024-06-27 15:32 UTC, feoche requested changes
- [ ] Set icon font-size to `0.875rem`

2024-06-28 12:42 UTC, feoche approved these changes

2024-06-28 14:54 UTC, aesteves60 approved these changes

2024-07-01 07:51 UTC, astagnol approved these changes

2024-07-01 07:59 UTC, merged