feat(card): implement component
ovh/design-system pull request #467
Opened 2024-06-14 09:02 UTC by Leotheluck

> Card is a component designed to be a container for displaying content and other elements to communicate information or feature a call-to-action within a page.

2024-06-14 09:10 UTC, dpellier requested changes

2024-06-14 09:10 UTC, dpellier commented on packages/ods/src/components/card/src/components/ods-card/ods-card.tsx
> +      <Host class={ 'ods-card' }>
direct string `class="ods-card"`

2024-06-14 09:10 UTC, dpellier commented on packages/ods/src/components/card/src/components/ods-card/ods-card.tsx
> +        <div class={ `ods-card__wrapper ods-card__wrapper--${this.color}` } part={ 'card' }>
why the extra div? you could just have put the style on the Host (and remove the part)

2024-06-17 12:41 UTC, astagnol requested changes

2024-06-17 12:41 UTC, astagnol commented on packages/storybook/stories/components/card/card.stories.ts
> +export const Color: StoryObj = {
We should display all available colors: neutral & primary

2024-06-17 12:41 UTC, astagnol commented on packages/storybook/stories/components/card/card.stories.ts
> +export const Default: StoryObj = {
I think instead of displaying "Default" example that shows nothing, we should do something similar to Icon example (with content here)

2024-06-17 13:27 UTC, dpellier approved these changes

2024-06-18 08:06 UTC, astagnol approved these changes

2024-06-18 08:12 UTC, aesteves60 approved these changes

2024-06-18 08:12 UTC, merged