Refactor/ods optimized icons
ovh/design-system pull request #468
Opened 2024-06-17 13:48 UTC by astagnol

### Icons have been optimized as following
- they're all 16X16px
- icons as "stroke" are now vectors so, they can be scaled up or down to any size without losing quality
- icons throwing warning"Glyph bbox was incorrect" in Firefox have been fixed
- some icons have been renamed to match better with what they are displaying; it will be easier to find them
- migration guide has been updated with a comparison before/after v18 for icon names

2024-06-18 07:32 UTC, dpellier requested changes
Select icons need to be updated (content value in css)

2024-06-18 09:55 UTC, feoche requested changes
## Global
- [x] Use same icon in "Documentation" and "Demo"

## Demo 
- [ ] Set `alt` attribute, as it is mandatory for a11y purposes

2024-06-18 14:03 UTC, dpellier approved these changes

2024-06-18 14:51 UTC, feoche approved these changes

2024-06-19 07:39 UTC, Leotheluck approved these changes

2024-06-19 09:50 UTC, aesteves60 approved these changes

2024-06-19 11:52 UTC, merged