refactor(range): implement component
ovh/design-system pull request #472
Opened 2024-07-01 14:11 UTC by aesteves60

2024-07-02 07:35 UTC, dpellier requested changes
Demo:
- if I change the `max` to a lower value than the current one, the tooltip does not update to the max value but keep the bigger one
- issue on the custom CSS example (tested on FF):
<img width="560" alt="Capture d’écran 2024-07-02 à 09 31 02" src="https://github.com/ovh/design-system/assets/1390934/9aa27b63-9095-4784-9679-9b3bfbb1a8a7">

- playing with step on dual leads to weird state:
<img width="799" alt="Capture d’écran 2024-07-02 à 09 44 52" src="https://github.com/ovh/design-system/assets/1390934/618bc5bf-c381-41e9-8346-3c246932aa89">

2024-07-02 08:43 UTC, astagnol requested changes
### Global
- we should not be able to click on the trackbar anymore (for both single and dual)
- "Dual: do not allow each handle to cross. They can be put on the same value, then max always stays on top"

2024-07-02 10:09 UTC, feoche requested changes
## Global
- [ ] Default value should be : `min:0`, `max:100` (as native Range does)
- [x] When no `value` is defined, it should have the same strategy as native Range does - see https://developer.mozilla.org/fr/docs/Web/HTML/Element/input/range#valeur
- [ ] There are misalignments between `ods-range`'s `value` and the inner's `input`'s `value` (especially tweaking `min` and `max` bounds)
- [ ] Range trackbar should not be clickable
- [ ] Dual Range : Values should keep a logical order, meaning we can't have a max bound before a min bound in DOM (issue especially on focus)
- [ ] Dual Range : setting `min` and/or `max` inside value bounds (thumbs) hides one of them

## Style
- [ ] Setting `isDisabled` and `hasError` to `true` should not display the error style (only disabled)
- [ ] Changing `step` messes up the thumb position on the Range
- [ ] Setting `min` to something greater than `value` breaks
- [ ] Setting `max` to something less than `value` puts Tooltip outside of Range

## Documentation
- [ ] All examples : Add extra top margin for tooltip
- [ ] Style customization : Messes up the range 
![image](https://github.com/ovh/design-system/assets/5332505/bea3d396-5164-4e88-8266-f99955f1cbe8)

2024-07-05 08:13 UTC, dpellier requested changes

2024-07-05 08:13 UTC, dpellier commented on packages/storybook/stories/components/range/documentation.mdx
> +<Canvas of={ RangeStories.Step } sourceState='shown' />
would be nice to add a dual example too

2024-07-15 13:17 UTC, dpellier requested changes
<img width="345" alt="Capture d’écran 2024-07-15 à 15 16 21" src="https://github.com/user-attachments/assets/2a63bff3-3c13-4ef7-aa72-66907bb6c8a4">

Doc generator seems unable to manage `[number, number]`, either try to fix it (if not much trouble) or use the `/** @docType ` tag

2024-07-17 15:16 UTC, dpellier requested changes

2024-07-17 15:16 UTC, dpellier commented on packages/ods/src/components/range/src/components/ods-range/ods-range.tsx
> +  onInputElChange(mutationList: MutationRecord[]): void {
put after lifecycle and set `private`

2024-07-17 15:16 UTC, dpellier commented on packages/ods/src/components/range/tests/behavior/ods-range.e2e.ts
> +describe('ods-range behavior', () => {
we went with the `behaviour` style for now, please update the directory name accordingly

2024-07-17 15:16 UTC, dpellier commented on packages/ods/src/style/_range.scss
> +    z-index: 2;
if this value is actually meant to be higher than the `z-index: 1` of `.ods-range__range-dual`, use a variable on the latest and set this to `$the-var + 1`

2024-07-17 16:00 UTC, aesteves60 commented on packages/ods/src/components/range/src/components/ods-range/ods-range.tsx
> +    this.value = this.defaultValue ?? this.min;
There a a weird when I set the value to null, the thumb is in the middel but there are no color on the track
![image](https://github.com/user-attachments/assets/73dd949c-431a-41ea-9eb6-7d14a7ee5df4)

2024-07-17 16:02 UTC, aesteves60 commented on packages/ods/src/components/range/src/components/ods-range/ods-range.tsx
> +    isDualRange(this.value) ? this.changeValues(this.value[0], this.value[1]) : this.changeValues(this.value ?? undefined);
Yeah but if I use `this.isDualRange` typescript don't use the guard and don't know the type of `value`

2024-07-18 07:15 UTC, aesteves60 commented on packages/ods/src/components/range/src/components/ods-range/ods-range.tsx
> +      }
Don't know this very usefull 👍

2024-07-18 08:36 UTC, astagnol approved these changes

2024-07-18 09:24 UTC, dpellier commented on packages/ods/src/components/range/src/components/ods-range/ods-range.tsx
> +    this.value = this.defaultValue ?? this.min;
Ok as it is the default browser rendering on empty value, but hide the tooltip if value is null

2024-07-18 14:45 UTC, dpellier approved these changes

2024-07-18 14:47 UTC, feoche approved these changes

2024-07-18 14:49 UTC, merged