feat(cart): add migration doc
ovh/design-system pull request #479
Opened 2024-07-16 09:46 UTC by dpellier

2024-07-17 08:07 UTC, Leotheluck commented on packages/storybook/stories/components/cart/migration.from.17.x.mdx
> +Plus to use this component, integrators had to learn about the 9 different interfaces and all the possible combinations.
Also, in order to use this component, the integrators had to learn about the 9 different interfaces and all their possible combinations.

2024-07-17 08:07 UTC, Leotheluck commented on packages/storybook/stories/components/cart/migration.from.17.x.mdx
> +ODS component tends to be presentational component, the internal logic should be handle by people integrating the component.
ODS components tend to be presentational, thus the internal logic should be handled by the integrators.

2024-07-17 08:07 UTC, Leotheluck commented on packages/storybook/stories/components/cart/migration.from.17.x.mdx
> +Current Cart implementation was trying to enforce some of the logic (ex: quantity computation).
The current implementation of Cart was trying to enforce some of the logic (e.g. quantity computation).

2024-07-17 08:07 UTC, Leotheluck commented on packages/storybook/stories/components/cart/migration.from.17.x.mdx
> +probably as a separate tag namespace.
It is possible, in the near future, that OVHcloud-oriented components like this one find their way back into ODS, probably as a separate tag namespace.

2024-07-17 08:14 UTC, feoche requested changes

2024-07-17 08:14 UTC, feoche commented on packages/storybook/stories/components/cart/migration.from.17.x.mdx
> +## OVH components?
I'd prefer to exclude this paragraph, as we are not able to know at which level component can be re-included inside ODS. It's something we need to communicate for sure, but preferably with direct teams.

2024-07-19 07:59 UTC, aesteves60 approved these changes

2024-07-19 08:35 UTC, astagnol approved these changes

2024-07-19 09:33 UTC, merged