fix(select): set color for selected option
ovh/design-system pull request #491
Opened 2024-07-24 12:26 UTC by skhamvon

Set color for selected option to primary-200

2024-07-24 13:27 UTC, aesteves60 approved these changes

2024-07-24 14:03 UTC, astagnol requested changes
Don't merge yet, just waiting for Design validation regarding this topic

2024-07-25 09:49 UTC, astagnol approved these changes

2024-07-25 15:53 UTC, feoche approved these changes

2024-07-26 07:50 UTC, Leotheluck approved these changes

2024-07-26 07:51 UTC, merged