refactor(docs): gallery page containing all component overviews
ovh/design-system pull request #504
Opened 2024-07-25 15:47 UTC by feoche

2024-07-26 07:17 UTC, aesteves60 requested changes

2024-07-26 07:17 UTC, aesteves60 commented on packages/storybook/stories/components/gallery.mdx
> +import { Default as Breadcrumb } from './breadcrumb/breadcrumb.stories';
On the first render the breadcrumb don't render correctly
![image](https://github.com/user-attachments/assets/6ddd4064-0b32-4971-ba31-e373e166842a)

2024-07-26 07:17 UTC, aesteves60 commented on packages/storybook/assets/css/gallery.css
> +  max-height: 150px;
this line cause trouble on the technical documentation 
![image](https://github.com/user-attachments/assets/5b0b4e5a-0a54-4544-927a-a6aa10ec0859)

2024-07-26 07:27 UTC, dpellier requested changes
- breadcrumb KO
- medium KO, need a story where it fits the container
- switch KO
- tabs KO

Need a

2024-07-26 07:27 UTC, dpellier commented on packages/storybook/assets/css/gallery.css
> +  position: absolute;
why?
this does only add more issues as you scroll outside of the padding box

2024-07-26 07:27 UTC, dpellier commented on packages/storybook/stories/components/gallery.mdx
> +<div class={ 'gallery--items' }>
no need for interpolation on static string, use `="....."` everywhere

2024-07-26 07:27 UTC, dpellier commented on packages/storybook/assets/css/gallery.css
> +.gallery--items {
if you want to use BEM notation you should treat those as block not modifier and have:
```
.gallery__items {

}

.gallery__items__item {
...
}

.gallery__items__item__title {
...
}
```

2024-07-26 13:09 UTC, dpellier requested changes

2024-07-26 13:09 UTC, dpellier commented on packages/storybook/assets/css/gallery.css
> +#gallery {
why not a class ?

2024-07-26 13:09 UTC, dpellier commented on packages/storybook/stories/components/gallery.mdx
> +      <Canvas of={ Accordion } sourceState='none' />
try to always use the same quote everywhere.
For HTML attribute, we use `"...."`
(check some of the Overview you've added, as they expose those as example code, like in ods-text story for example)

2024-07-29 09:18 UTC, Leotheluck approved these changes

2024-07-29 12:01 UTC, merged