docs(form-field): add examples for all form elements
ovh/design-system pull request #518
Opened 2024-07-31 16:33 UTC by feoche

2024-08-01 06:43 UTC, dpellier commented on packages/storybook/stories/components/form-field/form-field.stories.ts
> +  <ods-text id="form-field__checkbox-label" slot="label" preset="label">
FYI no need for the BEM notation on id, this is just for classes
`form-field-checkbox-label` would have been enough

2024-08-01 14:57 UTC, dpellier requested changes

2024-08-01 14:57 UTC, dpellier commented on packages/storybook/stories/components/form-field/form-field.stories.ts
> +      <ods-text class="form-field__checkbox__label" slot="label" preset="label">
no need for `ods-text` here just use native `label` otherwise you'll end up with two label tags

2024-08-01 14:57 UTC, dpellier commented on packages/storybook/stories/components/form-field/form-field.stories.ts
> +    <label for="input-id-example">
wrong id

2024-08-01 14:57 UTC, dpellier commented on packages/storybook/stories/components/form-field/form-field.stories.ts
> +  <ods-datepicker class="form-field__datepicker__field"></ods-datepicker>
If there is no style, do not use a class as a JS selector, prefer an id

2024-08-01 14:57 UTC, dpellier commented on packages/storybook/stories/components/form-field/form-field.stories.ts
> +      <ods-text class="form-field__radio__label" slot="label" preset="label">
remove ods-text

2024-08-01 14:57 UTC, dpellier commented on packages/storybook/stories/components/form-field/form-field.stories.ts
> +      <ods-text class="form-field__radio__label" slot="label" preset="label">
remove ods-text

2024-08-01 14:57 UTC, dpellier commented on packages/storybook/stories/components/form-field/form-field.stories.ts
> +        const maxCharactersElement = document.querySelector('.textarea__max-characters');
same prefer id when used only for JS selector

2024-08-01 14:57 UTC, dpellier commented on packages/storybook/stories/components/form-field/form-field.stories.ts
> +      const maxBound = document.querySelector('.range__max-bound');
same prefer id when used only for JS selector

2024-08-01 14:57 UTC, dpellier commented on packages/storybook/stories/components/form-field/form-field.stories.ts
> +      const timepicker = document.querySelector('.form-field__timepicker__field');
same prefer id when used only for JS selector

2024-08-02 06:44 UTC, dpellier requested changes

2024-08-02 06:44 UTC, dpellier commented on packages/storybook/stories/components/form-field/form-field.stories.ts
> +  <ods-text class="form-field__overview__helper" slot="helper" preset="caption">
not sure `caption` is the right tag here, this is not a table

2024-08-02 06:44 UTC, dpellier commented on packages/storybook/stories/components/form-field/form-field.stories.ts
> +    <ods-text class="form-field__range__sub-label" preset="caption">
same, not a caption

2024-08-05 07:07 UTC, astagnol approved these changes

2024-08-05 09:25 UTC, astagnol approved these changes

2024-08-05 09:36 UTC, merged