fix(tabs): border on all the width
ovh/design-system pull request #548
Opened 2024-08-21 14:55 UTC by aesteves60

2024-08-22 07:14 UTC, dpellier requested changes

2024-08-22 07:14 UTC, dpellier commented on packages/ods/src/components/tabs/src/components/ods-tabs/ods-tabs.scss
> +  overflow-y: auto;
`overflow-x` we want an horizontal scroll (it won't impact your tab rendering with the wrapper)

2024-08-22 07:14 UTC, dpellier commented on packages/ods/src/components/tabs/src/components/ods-tab/ods-tab.scss
> +  margin-bottom: -2px;
please use a shared variable for `margin-bottom` and `border-bottom` size here and `border-bottom` size in ods-tabs.scss

2024-08-22 07:14 UTC, dpellier commented on packages/ods/src/components/tabs/src/components/ods-tabs/ods-tabs.scss
> +  &-border {
- use `__` for BEM block
- use a more generic name, as this block contains the tabs, it's not just for the border (something like `__items` or `__wrapper` or `__container`)

2024-08-22 10:02 UTC, dpellier approved these changes

2024-08-22 15:20 UTC, feoche requested changes
## Global 
- [ ] When focusing first tab, outline is being cropped on the left part

2024-08-26 14:10 UTC, astagnol approved these changes

2024-08-26 14:31 UTC, feoche approved these changes

2024-08-26 15:29 UTC, merged