feat(button): can display an icon on the left or right
ovh/design-system pull request #575
Opened 2024-09-27 16:16 UTC by astagnol

2024-10-02 12:33 UTC, dpellier requested changes

2024-10-02 12:33 UTC, dpellier commented on packages/ods/src/components/button/src/components/ods-button/ods-button.tsx
> +  @Prop({ reflect: true }) public iconAlignment?: OdsButtonIconAlignment = ODS_BUTTON_ICON_ALIGNMENT.left;
though it will be removed with the doc refactor, you need to add an explicit `/** @docType OdsButtonIconAlignment */` here

2024-10-02 12:33 UTC, dpellier commented on packages/ods/src/components/button/src/components/ods-button/ods-button.tsx
> +            ${this.iconAlignment === 'right' ? 'ods-button__button--icon-right' : ''}
use enum value instead of 'right'

2024-10-02 12:33 UTC, dpellier commented on packages/storybook/stories/components/button/button.stories.ts
> +        defaultValue: { summary: ODS_BUTTON_ICON_ALIGNMENT.left },
add default value to the `args` also

2024-10-07 07:51 UTC, aesteves60 approved these changes

2024-10-07 13:04 UTC, merged