feat(global): add read-only tokens & apply style to components
ovh/design-system pull request #616
Opened 2024-10-30 14:31 UTC by astagnol

2024-10-30 14:36 UTC, dpellier requested changes
- add `isReadonly` control on select
- cursor on readonly select is a hand

2024-10-31 13:59 UTC, dpellier requested changes

2024-10-31 13:59 UTC, dpellier commented on packages/ods/src/components/select/src/components/ods-select/ods-select.scss
> -    cursor: pointer !important;
still at least one use-case to handle then:
- open a select by clicking on the input => the cursor become a `text` one

2024-10-31 15:59 UTC, aesteves60 approved these changes

2024-10-31 16:02 UTC, dpellier approved these changes

2024-10-31 16:02 UTC, merged