feat(text): change preset caption tag to span
ovh/design-system pull request #628
Opened 2024-11-08 14:30 UTC by astagnol

2024-11-08 15:53 UTC, dpellier requested changes
Would be nice to add somewhere in the doc that the `caption` preset is only about giving a custom style, but for actual `caption` (table) or `figcaption` (image) they should use the native tag using either an ods-text inside of it or the sass mixin

2024-11-12 13:53 UTC, dpellier requested changes

2024-11-12 13:53 UTC, dpellier commented on packages/storybook/stories/components/text/text.stories.ts
> +  table {
use a specific uniq id as this is apply to the whole page => this specifically apply on the `Properties` table on top of the page.

2024-11-12 13:53 UTC, dpellier commented on packages/storybook/stories/components/text/text.stories.ts
> +  caption {
use a specific uniq id as this is apply to the whole page

2024-11-12 13:53 UTC, dpellier commented on packages/storybook/stories/components/text/text.stories.ts
> +  img {
use a specific uniq id as this is apply to the whole page

2024-11-12 13:53 UTC, dpellier commented on packages/storybook/stories/components/text/text.stories.ts
> +      description: 'Caption preset is only custom styling. For `<caption>` or `<figcaption>`, use the native tag with ods-text or Sass mixin',
probably not needed here

2024-11-13 08:46 UTC, aesteves60 approved these changes

2024-11-13 13:51 UTC, merged