feat(input): add search type
ovh/design-system pull request #634
Opened 2024-11-19 08:49 UTC by astagnol

2024-11-19 13:10 UTC, dpellier requested changes

2024-11-19 13:30 UTC, aesteves60 requested changes
You nedd to increase the padding-right with search, clearable and is-masked
![image](https://github.com/user-attachments/assets/6d05ca23-dac6-4c29-8ba1-3f0f542a5e6b)

2024-11-20 08:23 UTC, dpellier requested changes
Still KO when `isMasked` is set
<img width="268" alt="Capture d’écran 2024-11-20 à 09 22 48" src="https://github.com/user-attachments/assets/6db0e1aa-c0cb-4a83-82b0-b3bdc389fcb8">

2024-11-20 10:11 UTC, dpellier approved these changes

2024-11-20 15:33 UTC, aesteves60 approved these changes

2024-11-20 15:43 UTC, merged