feat(range): add ticks props
ovh/design-system pull request #662
Opened 2024-12-06 15:36 UTC by aesteves60

2024-12-09 08:58 UTC, dpellier requested changes

2024-12-09 08:58 UTC, dpellier commented on packages/ods/src/components/range/src/components/ods-range/ods-range.tsx
> +  @State() private activatedTicks: number[] = [];
heep alphabetical order

2024-12-09 08:58 UTC, dpellier commented on packages/ods/src/components/range/src/components/ods-range/ods-range.scss
> +  padding-top: 5px;
should be computed from tick height and range thickness

2024-12-09 08:58 UTC, dpellier commented on packages/ods/src/components/range/src/components/ods-range/ods-range.scss
> +      width: 3px;
2px

2024-12-09 08:58 UTC, dpellier commented on packages/ods/src/components/range/src/components/ods-range/ods-range.scss
> +      height: 18px;
should be the same as the thumb, (declare a var that you'll use on the thumb style also)

2024-12-09 08:58 UTC, dpellier commented on packages/ods/src/style/_range.scss
> +    margin-top: 4px;
relative to what?

2024-12-09 10:17 UTC, dpellier commented on packages/ods/src/style/_range.scss
> +
remove empty line

2024-12-09 10:21 UTC, dpellier commented on packages/ods/src/style/_range.scss
> +    margin-top: 4px;
not event needed? should be overriden by the one declared above anyway

2024-12-09 10:22 UTC, dpellier requested changes

2024-12-09 10:22 UTC, dpellier commented on packages/ods/src/components/range/src/components/ods-range/ods-range.tsx
> +              style={{ left: `calc(${tick * ratio}% - 2px)` }}>
this `2` is in fact the half of the tick thickness

2024-12-09 13:29 UTC, dpellier requested changes
- need to add more space between text and thumb (especially when focused)
<img width="129" alt="Capture d’écran 2024-12-09 à 14 26 09" src="https://github.com/user-attachments/assets/ded265e5-cc68-4907-a996-7c8751c3d4f7">
<img width="110" alt="Capture d’écran 2024-12-09 à 14 26 11" src="https://github.com/user-attachments/assets/183449a6-1ea5-4d33-9a7d-e7f0d09f1937">


- KO on chromium when activating the ticks
<img width="154" alt="Capture d’écran 2024-12-09 à 14 26 34" src="https://github.com/user-attachments/assets/3a386ed2-9946-4f28-8d3c-2f511deb0aaa">
<img width="164" alt="Capture d’écran 2024-12-09 à 14 26 43" src="https://github.com/user-attachments/assets/b2908f35-161b-402b-bf60-10d588df2fb4">

2024-12-10 10:05 UTC, dpellier requested changes
The height of the ods-range element is now incorrect, with the extra space added to the texts.
<img width="384" alt="Capture d’écran 2024-12-10 à 11 02 28" src="https://github.com/user-attachments/assets/6259527e-4fe2-45ff-8856-4a87340c82b5">

The correct way would be to enforce an height on those texts and use it to compute the ods-range value (with the range height variable)

2024-12-10 15:39 UTC, dpellier approved these changes

2024-12-11 08:19 UTC, astagnol requested changes
Active ticks when Range is disabled are incorrect:
<img width="241" alt="Capture d’écran 2024-12-11 à 09 16 58" src="https://github.com/user-attachments/assets/ea5512ef-8856-4cde-b213-5922f2af2374">

2024-12-11 09:17 UTC, feoche commented
- [] On "Ticks" example (only single ones) in technical documentation, please remove `0` and `100` ticks

2024-12-11 13:24 UTC, merged