refactor(accordion): use the native behaviour & add methods
ovh/design-system pull request #668
Opened 2024-12-20 12:57 UTC by dpellier

2024-12-20 13:24 UTC, aesteves60 requested changes

2024-12-20 13:24 UTC, aesteves60 commented on packages/ods/src/components/accordion/src/components/ods-accordion/ods-accordion.tsx
> +          this.odsToggle.emit({ isOpen: this.detailsElement!.hasAttribute('open') });
```suggestion
          this.odsToggle.emit({ isOpen: this.detailsElement?.hasAttribute('open') ?? false });
```

2024-12-20 16:04 UTC, astagnol approved these changes

2024-12-23 09:13 UTC, aesteves60 approved these changes

2024-12-30 08:25 UTC, merged