feat(drawer): init component
ovh/design-system pull request #672
Opened 2024-12-31 14:23 UTC by aesteves60

2025-01-02 09:55 UTC, feoche requested changes

2025-01-02 09:55 UTC, feoche commented on packages/storybook/stories/components/drawer/drawer.stories.ts
> +    <ods-text preset="heading-4">Hello, world!</ods-text>
Maybe wrapping it into a <div> will improve its display to the user

2025-01-02 10:19 UTC, astagnol requested changes

2025-01-02 10:19 UTC, astagnol commented on packages/ods/src/components/drawer/src/components/ods-drawer/ods-drawer.scss
> +      animation: drawer-close-bottom 0.1s ease-in-out;
If I remember right, I think we defined that the default animation should be 300ms to be visually perceived by people. (and Modal should be updated in a separated PR)

2025-01-02 15:28 UTC, dpellier requested changes

2025-01-02 15:28 UTC, dpellier commented on packages/ods/src/components/drawer/src/components/ods-drawer/ods-drawer.tsx
> +      event.stopPropagation();
we may want to keep the propagation, as it may be needed for other content in the drawer (like for example, to hide a select dropdown)

2025-01-02 15:28 UTC, dpellier commented on packages/ods/src/style/_drawer.scss
> +  display: flex;
`display: block` would be more close to classic HTMElement rendering

2025-01-02 15:28 UTC, dpellier commented on packages/ods/src/style/_drawer.scss
> +  z-index: 1;
we should start to define ODS z-indexes to ensure proper order between all our overlays

2025-01-02 15:28 UTC, dpellier commented on packages/ods/src/style/_drawer.scss
> +  padding: 1rem;
we're mostly using `px` on other components

2025-01-02 15:28 UTC, dpellier commented on packages/ods/src/style/_drawer.scss
> +    height: 320px;
create a variable and use on each position

2025-01-02 15:28 UTC, dpellier commented on packages/storybook/stories/components/drawer/documentation.mdx
> +
space

2025-01-02 15:28 UTC, dpellier commented on packages/storybook/stories/components/drawer/documentation.mdx
> +- **Left/Right**: Covers 100% of the page height, with a default width of 320px and a maximum width of 100% - 3rem (48px)
I think this is yet to be implemented

2025-01-02 15:28 UTC, dpellier commented on packages/storybook/stories/components/drawer/documentation.mdx
> +  - By interacting with the same trigger used for expansion
not in the actual implementation, the backdrop prevent any click

2025-01-02 15:28 UTC, dpellier commented on packages/storybook/stories/components/drawer/documentation.mdx
> +- **Aria attributes**: The **Drawer** reacts to the aria-expanded attribute to indicate its state
missing

2025-01-02 15:28 UTC, dpellier commented on packages/ods/src/components/drawer/src/components/ods-drawer/ods-drawer.scss
> +  display: flex;
`display: block` would be more close to classic HTMElement rendering

2025-01-02 15:28 UTC, dpellier commented on packages/ods/src/components/drawer/src/components/ods-drawer/ods-drawer.tsx
> +      event.stopPropagation();
BTW in your example in the index.html, pressing Esc while the modal is open, close both, maybe something to check on modal side too

2025-01-10 10:05 UTC, aesteves60 commented on packages/ods/src/components/drawer/src/components/ods-drawer/ods-drawer.tsx
> +      event.stopPropagation();
Good on the select

2025-01-10 10:19 UTC, dpellier requested changes
Still waiting for anatomy picture
<img width="233" alt="Capture d’écran 2025-01-10 à 11 18 24" src="https://github.com/user-attachments/assets/eb8d350a-7812-4b1c-9589-e765abdf91ee" />

2025-01-10 10:19 UTC, dpellier commented on packages/ods/src/components/drawer/tests/navigation/ods-drawer.e2e.ts
> +      await page.keyboard.press('Tab');
why 3 tabs?

2025-01-10 10:19 UTC, dpellier commented on packages/storybook/src/components/gallery/Gallery.tsx
> +              <CanvasWithoutContext className={ styles['gallery__items__item__preview'] }
breaks the rendering style
<img width="820" alt="Capture d’écran 2025-01-10 à 11 17 35" src="https://github.com/user-attachments/assets/e846de6b-61e8-477c-8859-c0a7577a991a" />

2025-01-10 10:20 UTC, dpellier requested changes
Sources are not visible on Technical page

2025-01-10 10:22 UTC, dpellier requested changes
Triggering another drawer does close it immediatley on Technical example page.
- go to Drawer "Technical Information" page > Examples > Position
- click on "Trigger Drawer left" > Drawer open
- click on "Trigger Drawer bottom" > Drawer moves to bottom and closes

We would expect different drawers or just the position to change (like the Demo)

2025-01-13 14:05 UTC, aesteves60 commented on packages/ods/src/components/drawer/tests/navigation/ods-drawer.e2e.ts
> +      await page.keyboard.press('Tab');
The focus is first on the button trigger, the drawer and then on the content of the drawer

2025-01-14 09:04 UTC, dpellier requested changes

2025-01-16 08:42 UTC, dpellier requested changes

2025-01-16 08:42 UTC, dpellier commented on packages/ods/src/components/drawer/tests/navigation/ods-drawer.e2e.ts
> +      expect(await getFocusTagName()).toBe('BUTTON');
would be nice to differentiate this "button" from the trigger "button" to be sure that we focus the right one

2025-01-16 08:42 UTC, dpellier commented on packages/ods/src/components/modal/src/components/ods-modal/ods-modal.tsx
> +          tabindex={ -1 }>
hum is it really needed for modal?

2025-01-16 09:32 UTC, aesteves60 commented on packages/ods/src/components/modal/src/components/ods-modal/ods-modal.tsx
> +          tabindex={ -1 }>
Yes we have the same behaviour

2025-01-16 13:01 UTC, dpellier approved these changes

2025-01-17 08:26 UTC, astagnol approved these changes

2025-01-17 12:55 UTC, merged