feat(file): add file component
ovh/design-system pull request #70
Opened 2023-06-12 17:26 UTC by ady642

2023-06-12 17:58 UTC, ovh-cds commented
CDS Report build#700.0 ✘  
* 
  * build ✘

2023-06-14 08:14 UTC, ovh-cds commented
CDS Report build#705.0 ✘  
* 
  * build ✘

2023-06-19 07:23 UTC, ovh-cds commented
CDS Report build#718.0 ✘  
* 
  * build ✘

2023-06-20 08:56 UTC, ovh-cds commented
CDS Report build#727.0 ✘  
* 
  * build ✘

2023-06-20 13:53 UTC, ovh-cds commented
CDS Report build#731.0 ✘  
* 
  * build ✘

2023-06-21 14:25 UTC, ovh-cds commented
CDS Report build#741.0 ✘  
* 
  * build ✘

2023-06-22 07:29 UTC, ovh-cds commented
CDS Report build#742.0 ✘  
* 
  * build ✘

2023-06-26 07:35 UTC, ovh-cds commented
CDS Report build#766.0 ✘  
* 
  * build ✘

2023-06-26 10:04 UTC, ovh-cds commented
CDS Report build#772.0 ✘  
* 
  * build ✘

2023-06-27 07:13 UTC, ovh-cds commented
CDS Report build#784.0 ✘  
* 
  * build ✘

2023-06-28 09:20 UTC, ovh-cds commented
CDS Report build#807.0 ✘  
* 
  * build ✘

2023-06-28 12:14 UTC, ovh-cds commented
CDS Report build#809.0 ✘  
* 
  * build ✘

2023-06-28 15:58 UTC, ovh-cds commented
CDS Report build#819.0 ✘  
* 
  * build ✘

2023-06-29 14:36 UTC, ovh-cds commented
CDS Report build#821.0 ✘  
* 
  * build ✘

2023-06-29 16:11 UTC, ovh-cds commented
CDS Report build#822.0 ✘  
* 
  * build ✘

2023-06-30 05:44 UTC, ovh-cds commented
CDS Report build#823.0 ✘  
* 
  * build ✘

2023-07-03 08:57 UTC, ovh-cds commented
CDS Report build#829.0 ✘  
* 
  * build ✘

2023-07-03 12:43 UTC, ovh-cds commented
CDS Report build#831.0 ✘  
* 
  * build ✘

2023-07-03 16:07 UTC, ovh-cds commented
CDS Report build#834.0 ✘  
* 
  * build ✘

2023-07-03 23:19 UTC, ovh-cds commented
CDS Report build#835.0 ✘  
* 
  * build ✘

2023-07-04 12:32 UTC, ovh-cds commented
CDS Report build#836.0 ✘  
* 
  * build ✘

2023-07-04 15:34 UTC, ovh-cds commented
CDS Report build#839.0 ✘  
* 
  * build ✘

2023-07-05 14:54 UTC, ovh-cds commented
CDS Report build#851.0 ✘  
* 
  * build ✘

2023-07-07 07:37 UTC, ovh-cds commented
CDS Report build#868.0 ✘  
* 
  * build ✘

2023-07-12 07:32 UTC, dpellier requested changes
- There is a `cursor` style on the whole file-item row, though only icon seems clickable.
- E2e tests are failing when launched locally

2023-07-12 07:32 UTC, dpellier commented on packages/libraries/core/src/components/file/file-header/ods-file-header-controller.ts
> +    return this.component.acceptedTypes?.split(',').map((type) => type.split('/')[1].replace(';', '')).join(', ');
This won't work with types without `/` like: `'.doc,.docx,application/msword'` will fails
(please update unit test accordingly)

2023-07-12 07:32 UTC, dpellier commented on packages/libraries/core/src/components/file/file-item/ods-file-item-controller.spec.ts
> +        expect(controller.getSizeInKiloBytes(1000)).toEqual(1);
prefer `toBe` instead of `toEqual` for primitive values

2023-07-12 07:32 UTC, dpellier commented on packages/libraries/core/src/components/file/file-item/ods-file-item-controller.ts
> +    return Math.round(size / 1000);
Could be great to handle the NaN case also (as you have some for example in the e2e)

2023-07-12 07:32 UTC, dpellier commented on packages/libraries/core/src/components/file/ods-file-controller.ts
> +    return this.component.disabled || (this.component.files && this.component.files.length >= (this.component.maxFiles as number));
why is maxFiles not a number already?

2023-07-12 07:32 UTC, dpellier commented on packages/libraries/core/src/components/file/ods-file-controller.ts
> +    acceptedTypes.forEach((type, index) => {
you could do it in one row to avoid mutate the array:
```
this.component.acceptedTypes.split(',').map((type) => type.trim());
```

2023-07-12 07:32 UTC, dpellier commented on packages/libraries/core/src/components/file/ods-file-controller.ts
> +    if(this.component.maxFiles && this.component.files && (this.component?.files?.length + files.length) >= this.component.maxFiles) {
`?` should not be required as you test `this.component.files` before

2023-07-12 07:32 UTC, dpellier commented on packages/libraries/core/src/components/file/ods-file-controller.ts
> +    console.log('files', files)
to be removed

2023-07-12 07:32 UTC, dpellier commented on packages/libraries/core/src/components/file/ods-file-default-attributes.ts
> +  acceptedTypes: 'image/jpg, image/png, application/pdf',
not sure we should put types default values

2023-07-12 07:32 UTC, dpellier commented on packages/specifications/components/file/specifications-file.mdx
> +[//]: # (import Specs from '@ovhcloud/ods-core/src/components/file/docs/spec.md';)
This should be uncommented to fix the empty Specifications page on storybook

2023-07-12 07:32 UTC, dpellier commented on packages/stencil/components/file/package.json
> +  "version": "13.0.1",
update to latest ODS version

2023-07-12 07:32 UTC, dpellier commented on packages/stencil/components/file/react/package.json
> +    "@ovhcloud/ods-stencil-file": "^13.0.1",
update to latest ODS version

2023-07-12 07:32 UTC, dpellier commented on packages/stencil/components/file/vue/package.json
> +  "version": "13.0.1",
update to latest ODS version

2023-07-12 07:32 UTC, dpellier commented on packages/stencil/components/file/vue/package.json
> +    "@ovhcloud/ods-stencil-file": "^13.0.1"
update to latest ODS version

2023-07-12 07:32 UTC, dpellier commented on packages/stencil/components/file/src/components/osds-file/osds-file-header/osds-file-header.tsx
> +              <span class='ods-file__dropzone__header__title__label '>Glisser-déposer une pièce jointe</span>
We are not managing any labels for now as we don't have any i18n system.
Static strings should be set as attributes

2023-07-12 07:32 UTC, dpellier commented on packages/stencil/components/file/stencil.config.ts
> +    excludeComponents: []
add components used on global files

2023-07-12 07:32 UTC, dpellier commented on packages/stencil/components/file/stencil.config.ts
> +    excludeComponents: []
add components used on global files

2023-07-12 07:32 UTC, dpellier commented on packages/stencil/components/tsconfig.components.dev.json
> +    "file-item/src",
only file should be enough

2023-07-12 07:32 UTC, dpellier commented on packages/stencil/components/tsconfig.components.prod.json
> +    "file-item/src",
only file should be enough

2023-07-12 07:32 UTC, dpellier commented on packages/stencil/components/tsconfig.components.test.json
> +    "file-item/src",
only file should be enough

2023-07-12 07:59 UTC, aesteves60 commented on packages/libraries/core/src/components/file/ods-file-controller.ts
> +      && this.component.files.every((file) => file.progress === 100);
```suggestion
      this.component.files?.every((file) => file.progress === 100) || false;
```
not need the previous line

2023-07-12 08:01 UTC, dpellier commented on packages/libraries/core/src/components/file/ods-file-controller.ts
> +    return this.component.disabled || (this.component.files && this.component.files.length >= (this.component.maxFiles as number));
then you should instead check if the value is defined before the `>=`
```
    return this.component.disabled || (this.component.maxFiles && this.component.files && this.component.files.length >= this.component.maxFiles);
```

2023-07-12 12:44 UTC, astagnol requested changes
- disabled: all content doesn't have expected opacity
![Capture d’écran 2023-07-12 à 14 32 30](https://github.com/ovh/design-system/assets/53512103/18938691-f019-4572-a5a3-c9f5d6fcd881)

- file item label should not be color error-600
![Capture d’écran 2023-07-12 à 14 40 55](https://github.com/ovh/design-system/assets/53512103/9ffa9ec8-8f76-4586-bc08-d1406fc1cc92)

- maxFiles is working for drag&drop but not by click on "sélectionner un fichier", you can add more than the maximum
![Capture d’écran 2023-07-12 à 14 43 54](https://github.com/ovh/design-system/assets/53512103/ca849b9b-2a6b-4f15-821f-3092e70ff9df)

2023-07-17 07:14 UTC, dpellier requested changes
I still have failing e2e tests, seems like an issue with the time some test takes to start, maybe a change in the config is needed
<img width="877" alt="Capture d’écran 2023-07-17 à 09 13 09" src="https://github.com/ovh/design-system/assets/1390934/7e319747-91b5-4fda-8596-5901b81c8928">
<img width="911" alt="Capture d’écran 2023-07-17 à 09 13 18" src="https://github.com/ovh/design-system/assets/1390934/0e5ef781-9b45-48e6-b713-ac1376773dbe">

2023-07-17 07:14 UTC, dpellier commented on packages/libraries/core/src/components/file/ods-file-controller.ts
> +      alert(`ods-file: too many files selected. Max files is ${this.component.maxFiles}`);
no `alert` on final code, emit an Error instead

2023-07-17 07:14 UTC, dpellier commented on packages/libraries/core/src/components/file/ods-file-default-attributes.ts
> +  selectFilesLabel: 'sélectionner un fichier'
To Be Discussed: do we set defaut french value or move from ods every text/label?

2023-07-17 07:14 UTC, dpellier commented on packages/stencil/components/file/src/components/osds-file/osds-file.scss
> +    background-color: white;
we should not have specific color like that set in the code, use theme variable

2023-07-17 08:58 UTC, ady642 commented on packages/libraries/core/src/components/file/file-header/ods-file-header-default-attributes.ts
> +  acceptedTypes: 'image/jpg, image/png, application/pdf',
ok but its more practical to have an empty string

2023-07-17 08:59 UTC, ady642 commented on packages/libraries/core/src/components/file/file-header/ods-file-header-default-attributes.ts
> +  acceptedTypes: 'image/jpg, image/png, application/pdf',
I use odsFileDefault.acceptedTypes for odsFileHeaderDefaultAttributes, like this we cant have differences between files

2023-07-19 13:57 UTC, dpellier approved these changes

2023-07-20 14:11 UTC, aesteves60 approved these changes

2023-07-25 13:55 UTC, ovh-cds commented
CDS Report build-storybook#999.0 ✘  
* 
  * build ✘

2023-07-27 09:54 UTC, feoche commented
- [ ] Error slot should not replace helper slot
> When having an error on a field, the error slot should not remove the helper slot

2023-08-25 09:50 UTC, ovh-cds commented
CDS Report build#1293.0 ✘  
* 
  * build ✘

2023-10-06 09:54 UTC, closed without merging