feat(location-tile): deprecated component
ovh/design-system pull request #92
Opened 2023-06-30 14:02 UTC by aesteves60

2023-07-03 07:52 UTC, aesteves60 commented
Fixer link + use osds-message

2023-07-03 08:51 UTC, dpellier approved these changes

2023-07-03 09:02 UTC, astagnol approved these changes

2023-07-05 07:46 UTC, dpellier requested changes
Update with https://github.com/ovh/design-system/pull/91

2023-07-06 08:28 UTC, astagnol approved these changes

2023-07-06 08:34 UTC, merged