WIP: feat(pagination): add tooltip on arrow
ovh/design-system pull request #93
Opened 2023-07-04 14:22 UTC by aesteves60

2023-07-06 12:09 UTC, astagnol requested changes
![Capture d’écran 2023-07-06 à 10 54 57](https://github.com/ovh/design-system/assets/53512103/1c7390aa-5c17-4935-8976-247093b3c5b8)
Tooltip surface max-width used in Pagination should be 300px

In Storybook, we're losing focus when typing in labelTooltipPrevious & labelTooltipNext fields

2023-07-11 07:02 UTC, dpellier commented on packages/stencil/components/pagination/src/components/osds-pagination/osds-pagination.tsx
> +            { isLeft ? this.labelTooltipPrevious : this.labelTooltipNext }
did you try using `key` instead to trigger rerender on change?
`forceUpdate` on the whole element is quite costly, would be nice to avoid using it

2023-07-17 13:54 UTC, dpellier approved these changes

2023-07-17 16:53 UTC, astagnol requested changes

2023-07-17 16:53 UTC, astagnol commented on packages/libraries/cdk/src/components/surface/strategies/symmetry/ocdk-surface-symmetry.bl-tl.ts
> +          maxWidth: (opt) => opt.inspections.comfort.availableLeft,
Should be availableRight instead of left

2023-07-18 07:54 UTC, astagnol approved these changes

2023-07-18 09:19 UTC, merged